package com.lvmama.comm.bee.po.prod;

import java.io.Serializable;

public class ViewPageTag implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -9064379019921365026L;

	private String tagName;
    public String getTagName() {
		return tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VIEW_PAGE_TAG.PAGE_TAG_ID
     *
     * @ibatorgenerated Wed Jun 02 13:02:17 CST 2010
     */
    private Long pageTagId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VIEW_PAGE_TAG.PAGE_ID
     *
     * @ibatorgenerated Wed Jun 02 13:02:17 CST 2010
     */
    private Long pageId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VIEW_PAGE_TAG.TAG_ID
     *
     * @ibatorgenerated Wed Jun 02 13:02:17 CST 2010
     */
    private Long tagId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VIEW_PAGE_TAG.PAGE_TAG_ID
     *
     * @return the value of VIEW_PAGE_TAG.PAGE_TAG_ID
     *
     * @ibatorgenerated Wed Jun 02 13:02:17 CST 2010
     */
    public Long getPageTagId() {
        return pageTagId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VIEW_PAGE_TAG.PAGE_TAG_ID
     *
     * @param pageTagId the value for VIEW_PAGE_TAG.PAGE_TAG_ID
     *
     * @ibatorgenerated Wed Jun 02 13:02:17 CST 2010
     */
    public void setPageTagId(Long pageTagId) {
        this.pageTagId = pageTagId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VIEW_PAGE_TAG.PAGE_ID
     *
     * @return the value of VIEW_PAGE_TAG.PAGE_ID
     *
     * @ibatorgenerated Wed Jun 02 13:02:17 CST 2010
     */
    public Long getPageId() {
        return pageId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VIEW_PAGE_TAG.PAGE_ID
     *
     * @param pageId the value for VIEW_PAGE_TAG.PAGE_ID
     *
     * @ibatorgenerated Wed Jun 02 13:02:17 CST 2010
     */
    public void setPageId(Long pageId) {
        this.pageId = pageId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VIEW_PAGE_TAG.TAG_ID
     *
     * @return the value of VIEW_PAGE_TAG.TAG_ID
     *
     * @ibatorgenerated Wed Jun 02 13:02:17 CST 2010
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VIEW_PAGE_TAG.TAG_ID
     *
     * @param tagId the value for VIEW_PAGE_TAG.TAG_ID
     *
     * @ibatorgenerated Wed Jun 02 13:02:17 CST 2010
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }
}