<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<script src='<c:url value="/js/pandora-dialog.js/"/>'></script>
<script src='<c:url value="/js/jquery.lvtip.js/"/>'></script>
<script src='<c:url value="/js/My97DatePicker/WdatePicker.js/"/>'></script>
<script src='<c:url value="/js/lvmama-dialog.js/"/>'></script>
<script src='<c:url value="/js/jquery.validate.min.js/"/>'></script>
<script src='<c:url value="/js/jquery.validate.expand.js/"/>'></script>
<script src='<c:url value="/js/jquery.metadata.js/"/>'></script>
<script src='<c:url value="/js/jquery.form.js/"/>'></script>
<script src='<c:url value="/js/validate.js/"/>'></script>
<script src='<c:url value="/js/remoteUrlLoad.js/"/>'></script>