package com.lvmama.comm.pet.po.sup;

import java.io.Serializable;

public class MetaSettlement implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 8026938753569592298L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column META_SETTLEMENT.SETTLEMENT_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private Long settlementId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column META_SETTLEMENT.META_PRODUCT_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private Long metaProductId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column META_SETTLEMENT.TARGET_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private Long targetId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column META_SETTLEMENT.SETTLEMENT_PERIOD
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private String settlementPeriod;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column META_SETTLEMENT.SETTLEMENT_DIRECTION
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private String settlementDirection;
    private String bizType;
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column META_SETTLEMENT.SETTLEMENT_ID
     *
     * @return the value of META_SETTLEMENT.SETTLEMENT_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public Long getSettlementId() {
        return settlementId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column META_SETTLEMENT.SETTLEMENT_ID
     *
     * @param settlementId the value for META_SETTLEMENT.SETTLEMENT_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setSettlementId(Long settlementId) {
        this.settlementId = settlementId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column META_SETTLEMENT.META_PRODUCT_ID
     *
     * @return the value of META_SETTLEMENT.META_PRODUCT_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public Long getMetaProductId() {
        return metaProductId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column META_SETTLEMENT.META_PRODUCT_ID
     *
     * @param metaProductId the value for META_SETTLEMENT.META_PRODUCT_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setMetaProductId(Long metaProductId) {
        this.metaProductId = metaProductId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column META_SETTLEMENT.TARGET_ID
     *
     * @return the value of META_SETTLEMENT.TARGET_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public Long getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column META_SETTLEMENT.TARGET_ID
     *
     * @param targetId the value for META_SETTLEMENT.TARGET_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column META_SETTLEMENT.SETTLEMENT_PERIOD
     *
     * @return the value of META_SETTLEMENT.SETTLEMENT_PERIOD
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public String getSettlementPeriod() {
        return settlementPeriod;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column META_SETTLEMENT.SETTLEMENT_PERIOD
     *
     * @param settlementPeriod the value for META_SETTLEMENT.SETTLEMENT_PERIOD
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setSettlementPeriod(String settlementPeriod) {
        this.settlementPeriod = settlementPeriod;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column META_SETTLEMENT.SETTLEMENT_DIRECTION
     *
     * @return the value of META_SETTLEMENT.SETTLEMENT_DIRECTION
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public String getSettlementDirection() {
        return settlementDirection;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column META_SETTLEMENT.SETTLEMENT_DIRECTION
     *
     * @param settlementDirection the value for META_SETTLEMENT.SETTLEMENT_DIRECTION
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setSettlementDirection(String settlementDirection) {
        this.settlementDirection = settlementDirection;
    }

	public String getBizType() {
		return bizType;
	}

	public void setBizType(String bizType) {
		this.bizType = bizType;
	}
    
}