package com.lvmama.comm.pet.po.sup;

import java.io.Serializable;

public class MetaBCertificate implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -4918292283448061628L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column META_B_CERTIFICATE.PRODUCT_CERTIFICATE_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private Long productCertificateId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column META_B_CERTIFICATE.META_PRODUCT_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private Long metaProductId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column META_B_CERTIFICATE.TARGET_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private Long targetId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column META_B_CERTIFICATE.BCERTIFICATE_TYPE
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private String bcertificateType;
    private String bizType;
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column META_B_CERTIFICATE.PRODUCT_CERTIFICATE_ID
     *
     * @return the value of META_B_CERTIFICATE.PRODUCT_CERTIFICATE_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public Long getProductCertificateId() {
        return productCertificateId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column META_B_CERTIFICATE.PRODUCT_CERTIFICATE_ID
     *
     * @param productCertificateId the value for META_B_CERTIFICATE.PRODUCT_CERTIFICATE_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setProductCertificateId(Long productCertificateId) {
        this.productCertificateId = productCertificateId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column META_B_CERTIFICATE.META_PRODUCT_ID
     *
     * @return the value of META_B_CERTIFICATE.META_PRODUCT_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public Long getMetaProductId() {
        return metaProductId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column META_B_CERTIFICATE.META_PRODUCT_ID
     *
     * @param metaProductId the value for META_B_CERTIFICATE.META_PRODUCT_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setMetaProductId(Long metaProductId) {
        this.metaProductId = metaProductId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column META_B_CERTIFICATE.TARGET_ID
     *
     * @return the value of META_B_CERTIFICATE.TARGET_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public Long getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column META_B_CERTIFICATE.TARGET_ID
     *
     * @param targetId the value for META_B_CERTIFICATE.TARGET_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column META_B_CERTIFICATE.BCERTIFICATE_TYPE
     *
     * @return the value of META_B_CERTIFICATE.BCERTIFICATE_TYPE
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public String getBcertificateType() {
        return bcertificateType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column META_B_CERTIFICATE.BCERTIFICATE_TYPE
     *
     * @param bcertificateType the value for META_B_CERTIFICATE.BCERTIFICATE_TYPE
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setBcertificateType(String bcertificateType) {
        this.bcertificateType = bcertificateType;
    }

	public String getBizType() {
		return bizType;
	}

	public void setBizType(String bizType) {
		this.bizType = bizType;
	}
}