package com.lvmama.comm.pet.po.sup;

import java.io.Serializable;

public class MetaPerform implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -7180015744853120404L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column META_PERFORM.PRODUCT_PERFORM_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private Long productPerformId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column META_PERFORM.TARGET_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private Long targetId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column META_PERFORM.META_PRODUCT_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private Long metaProductId;
    private String bizType;
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column META_PERFORM.PRODUCT_PERFORM_ID
     *
     * @return the value of META_PERFORM.PRODUCT_PERFORM_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public Long getProductPerformId() {
        return productPerformId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column META_PERFORM.PRODUCT_PERFORM_ID
     *
     * @param productPerformId the value for META_PERFORM.PRODUCT_PERFORM_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setProductPerformId(Long productPerformId) {
        this.productPerformId = productPerformId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column META_PERFORM.TARGET_ID
     *
     * @return the value of META_PERFORM.TARGET_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public Long getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column META_PERFORM.TARGET_ID
     *
     * @param targetId the value for META_PERFORM.TARGET_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column META_PERFORM.META_PRODUCT_ID
     *
     * @return the value of META_PERFORM.META_PRODUCT_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public Long getMetaProductId() {
        return metaProductId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column META_PERFORM.META_PRODUCT_ID
     *
     * @param metaProductId the value for META_PERFORM.META_PRODUCT_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setMetaProductId(Long metaProductId) {
        this.metaProductId = metaProductId;
    }

	public String getBizType() {
		return bizType;
	}

	public void setBizType(String bizType) {
		this.bizType = bizType;
	}

}