package com.lvmama.comm.pet.po.sup;

import java.io.Serializable;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang3.StringUtils;

import com.lvmama.comm.utils.DateUtil;
import com.lvmama.comm.vo.Constant;

public class SupContract implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 6472197907763420727L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SUP_CONTRACT.CONTRACT_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private Long contractId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SUP_CONTRACT.CONTRACT_NAME
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private String contractName;

    private String contractNo;
    
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SUP_CONTRACT.SIGN_DATE
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private Date signDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SUP_CONTRACT.SUMMARY
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private String summary;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SUP_CONTRACT.START_DATE
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private Date beginDate;
    
    
    private Long orgId;
    
    

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SUP_CONTRACT.END_DATE
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private Date endDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SUP_CONTRACT.SUPPLIER_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private Long supplierId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SUP_CONTRACT.CONTRACT_STATUS
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private String contractStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SUP_CONTRACT.CONTRACT_TYPE
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private String contractType;

    private Date createTime;
    
    private String arranger;
    
    private String partyA;
    
    private Long managerId;
    
    private String supplierName;
    
    private String managerName;
    
    private String finAccountingEntityName;
    
    //绑定供应商的方式
    private String bindSupplierType;
    
    private String contractAudit;
    
    private String operateName;
    
    //上传文件表里的合同id
    private Long fsCId;
    
    private List<SupContractFs> fsList=Collections.emptyList();
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SUP_CONTRACT.CONTRACT_ID
     *
     * @return the value of SUP_CONTRACT.CONTRACT_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public Long getContractId() {
        return contractId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SUP_CONTRACT.CONTRACT_ID
     *
     * @param contractId the value for SUP_CONTRACT.CONTRACT_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setContractId(Long contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SUP_CONTRACT.CONTRACT_NAME
     *
     * @return the value of SUP_CONTRACT.CONTRACT_NAME
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public String getContractName() {
        return contractName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SUP_CONTRACT.CONTRACT_NAME
     *
     * @param contractName the value for SUP_CONTRACT.CONTRACT_NAME
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setContractName(String contractName) {
        this.contractName = contractName;
    }

    public String getContractNo() {
		return contractNo;
	}

	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SUP_CONTRACT.SIGN_DATE
     *
     * @return the value of SUP_CONTRACT.SIGN_DATE
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public Date getSignDate() {
        return signDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SUP_CONTRACT.SIGN_DATE
     *
     * @param signDate the value for SUP_CONTRACT.SIGN_DATE
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setSignDate(Date signDate) {
        this.signDate = signDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SUP_CONTRACT.SUMMARY
     *
     * @return the value of SUP_CONTRACT.SUMMARY
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SUP_CONTRACT.SUMMARY
     *
     * @param summary the value for SUP_CONTRACT.SUMMARY
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SUP_CONTRACT.BEGIN_DATE
     *
     * @return the value of SUP_CONTRACT.BEGIN_DATE
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public Date getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SUP_CONTRACT.BEGIN_DATE
     *
     * @param beginDate the value for SUP_CONTRACT.BEGIN_DATE
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SUP_CONTRACT.END_DATE
     *
     * @return the value of SUP_CONTRACT.END_DATE
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SUP_CONTRACT.END_DATE
     *
     * @param endDate the value for SUP_CONTRACT.END_DATE
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SUP_CONTRACT.SUPPLIER_ID
     *
     * @return the value of SUP_CONTRACT.SUPPLIER_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public Long getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SUP_CONTRACT.SUPPLIER_ID
     *
     * @param supplierId the value for SUP_CONTRACT.SUPPLIER_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setSupplierId(Long supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SUP_CONTRACT.CONTRACT_STATUS
     *
     * @return the value of SUP_CONTRACT.CONTRACT_STATUS
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public String getContractStatus() {
        return contractStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SUP_CONTRACT.CONTRACT_STATUS
     *
     * @param contractStatus the value for SUP_CONTRACT.CONTRACT_STATUS
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setContractStatus(String contractStatus) {
        this.contractStatus = contractStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SUP_CONTRACT.CONTRACT_TYPE
     *
     * @return the value of SUP_CONTRACT.CONTRACT_TYPE
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public String getContractType() {
        return contractType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SUP_CONTRACT.CONTRACT_TYPE
     *
     * @param contractType the value for SUP_CONTRACT.CONTRACT_TYPE
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setContractType(String contractType) {
        this.contractType = contractType;
    }

    public String getZhContractType() {
		return Constant.CONTRACT_TYPE.getCnName(contractType);
    }
    
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getArranger() {
		return arranger;
	}

	public void setArranger(String arranger) {
		this.arranger = arranger;
	}

	public Long getOrgId() {
		return orgId;
	}

	public void setOrgId(Long orgId) {
		this.orgId = orgId;
	}

	public String getPartyA() {
		return partyA;
	}

	public void setPartyA(String partyA) {
		this.partyA = partyA;
	}

	public Long getManagerId() {
		return managerId;
	}

	public void setManagerId(Long managerId) {
		this.managerId = managerId;
	}
	
	public String getZhDateDiff() {
		if(this.getEndDate() != null) {
			Date date = DateUtil.getTodayYMDDate();
			if(this.getEndDate().after(date)) {
				return (this.getEndDate().getTime() - date.getTime())/1000/60/60/24 + "天";
			}
		}
		return "0天";
	}

	public String getSupplierName() {
		return supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	public String getManagerName() {
		return managerName;
	}

	public void setManagerName(String managerName) {
		this.managerName = managerName;
	}

	public String getFinAccountingEntityName() {
		return finAccountingEntityName;
	}

	public void setFinAccountingEntityName(String finAccountingEntityName) {
		this.finAccountingEntityName = finAccountingEntityName;
	}

	public String getOperateName() {
		return operateName;
	}

	public void setOperateName(String operateName) {
		this.operateName = operateName;
	}

	public boolean isCreateSupplier(){
		return StringUtils.equals(this.getBindSupplierType(), Constant.CONTACT_SUPPLIER_TYPE.CREATE.name()); 
	}
	
	public String getBindSupplierType() {
		return bindSupplierType;
	}

	public void setBindSupplierType(String bindSupplierType) {
		this.bindSupplierType = bindSupplierType;
	}

	public String getContractAudit() {
		return contractAudit;
	}

	public void setContractAudit(String contractAudit) {
		this.contractAudit = contractAudit;
	}
	
	public String getZhContractStatus() {
		return Constant.CONTRACT_STATUS.getCnName(this.getContractStatus());
	}

	public List<SupContractFs> getFsList() {
		return fsList;
	}

	public void setFsList(List<SupContractFs> fsList) {
		this.fsList = fsList;
	}
	
	public String getZhContractAudit() {
		  return Constant.CONTRACT_AUDIT.getCnName(this.contractAudit);
	}

	public Long getFsCId() {
		return fsCId;
	}

	public void setFsCId(Long fsCId) {
		this.fsCId = fsCId;
	}

}