//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.25 at 03:35:49 ���� CST 
//


package com.lvmama.passport.processor.impl.client.jiuwang.model.v1.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 【畅游通提供】【订单】获取订单信息（getOrderByOTA）
 * 
 * <p>Java class for GetOrderByOTAResponseBody complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetOrderByOTAResponseBody">
 *   &lt;complexContent>
 *     &lt;extension base="{http://tour.ectrip.com/2014/QMResponseSchema}ResponseBody">
 *       &lt;sequence>
 *         &lt;element name="orderInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="partnerorderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="orderStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="orderQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="eticketNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="eticketSended" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="useQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="consumeInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetOrderByOTAResponseBody", propOrder = {
    "orderInfo"
})
public class GetOrderByOTAResponseBody
    extends ResponseBody
{

    @XmlElement(required = true)
    protected GetOrderByOTAResponseBody.OrderInfo orderInfo;

    /**
     * Gets the value of the orderInfo property.
     *
     * @return
     *     possible object is
     *     {@link GetOrderByOTAResponseBody.OrderInfo }
     *
     */
    public GetOrderByOTAResponseBody.OrderInfo getOrderInfo() {
        return orderInfo;
    }

    /**
     * Sets the value of the orderInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link GetOrderByOTAResponseBody.OrderInfo }
     *
     */
    public void setOrderInfo(GetOrderByOTAResponseBody.OrderInfo value) {
        this.orderInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="partnerorderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="orderStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="orderQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="eticketNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="eticketSended" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="useQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="consumeInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "partnerorderId",
        "orderStatus",
        "orderQuantity",
        "eticketNo",
        "eticketSended",
        "useQuantity",
        "consumeInfo"
    })
    public static class OrderInfo {

        @XmlElement(required = true)
        protected String partnerorderId;
        @XmlElement(required = true)
        protected String orderStatus;
        @XmlElement(required = true)
        protected String orderQuantity;
        @XmlElement(required = true)
        protected String eticketNo;
        @XmlElement(required = true)
        protected String eticketSended;
        @XmlElement(required = true)
        protected String useQuantity;
        @XmlElement(required = true)
        protected String consumeInfo;

        /**
         * Gets the value of the partnerorderId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPartnerorderId() {
            return partnerorderId;
        }

        /**
         * Sets the value of the partnerorderId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPartnerorderId(String value) {
            this.partnerorderId = value;
        }

        /**
         * Gets the value of the orderStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderStatus() {
            return orderStatus;
        }

        /**
         * Sets the value of the orderStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderStatus(String value) {
            this.orderStatus = value;
        }

        /**
         * Gets the value of the orderQuantity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderQuantity() {
            return orderQuantity;
        }

        /**
         * Sets the value of the orderQuantity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderQuantity(String value) {
            this.orderQuantity = value;
        }

        /**
         * Gets the value of the eticketNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEticketNo() {
            return eticketNo;
        }

        /**
         * Sets the value of the eticketNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEticketNo(String value) {
            this.eticketNo = value;
        }

        /**
         * Gets the value of the eticketSended property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEticketSended() {
            return eticketSended;
        }

        /**
         * Sets the value of the eticketSended property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEticketSended(String value) {
            this.eticketSended = value;
        }

        /**
         * Gets the value of the useQuantity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUseQuantity() {
            return useQuantity;
        }

        /**
         * Sets the value of the useQuantity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUseQuantity(String value) {
            this.useQuantity = value;
        }

        /**
         * Gets the value of the consumeInfo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConsumeInfo() {
            return consumeInfo;
        }

        /**
         * Sets the value of the consumeInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConsumeInfo(String value) {
            this.consumeInfo = value;
        }

    }

}
