//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.25 at 03:35:49 ���� CST 
//


package com.lvmama.passport.processor.impl.client.jiuwang.model.v1.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * 【畅游通提供】【产品】OTA获取产品信息接口（getProductByOTA）
 * 
 * <p>Java class for GetProductByOTAResponseBody complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetProductByOTAResponseBody">
 *   &lt;complexContent>
 *     &lt;extension base="{http://tour.ectrip.com/2014/QMResponseSchema}ResponseBody">
 *       &lt;sequence>
 *         &lt;element name="count" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="productInfos">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="productInfo" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="baseInfo">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="resourceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="sights">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="sight" maxOccurs="unbounded">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="sightName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="productName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="bookConfig">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="paymentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="advanceOption">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="bookAdvanceDay" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="bookAdvanceTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="useAdvanceHour" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="autoCancelTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="bookPersonType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="visitPersonRequiredForQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="priceConfig">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="validType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="daysAfterUseDateValid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="calendarPrices" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="calendarPrice" maxOccurs="unbounded">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="useDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="marketPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="sellPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="sellstock" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="productDescription">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="remind" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="refundOption">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="canRefund" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="refundApplyTimeBeforeValidEndDay" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="refundCharge" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="refundInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="otherConfig">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="smsTemplet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="eticketType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetProductByOTAResponseBody", propOrder = {
    "count",
    "productInfos"
})
public class GetProductByOTAResponseBody
    extends ResponseBody
{

    @XmlElement(required = true)
    protected String count;
    @XmlElement(required = true)
    protected GetProductByOTAResponseBody.ProductInfos productInfos;

    /**
     * Gets the value of the count property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCount(String value) {
        this.count = value;
    }

    /**
     * Gets the value of the productInfos property.
     *
     * @return
     *     possible object is
     *     {@link GetProductByOTAResponseBody.ProductInfos }
     *
     */
    public GetProductByOTAResponseBody.ProductInfos getProductInfos() {
        return productInfos;
    }

    /**
     * Sets the value of the productInfos property.
     *
     * @param value
     *     allowed object is
     *     {@link GetProductByOTAResponseBody.ProductInfos }
     *
     */
    public void setProductInfos(GetProductByOTAResponseBody.ProductInfos value) {
        this.productInfos = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="productInfo" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="baseInfo">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="resourceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="sights">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="sight" maxOccurs="unbounded">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="sightName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="productName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="bookConfig">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="paymentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="advanceOption">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="bookAdvanceDay" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="bookAdvanceTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="useAdvanceHour" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="autoCancelTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="bookPersonType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="visitPersonRequiredForQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="priceConfig">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="validType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="daysAfterUseDateValid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="calendarPrices" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="calendarPrice" maxOccurs="unbounded">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="useDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="marketPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="sellPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="sellstock" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="productDescription">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="remind" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="refundOption">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="canRefund" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="refundApplyTimeBeforeValidEndDay" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="refundCharge" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="refundInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="otherConfig">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="smsTemplet" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="eticketType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "productInfo"
    })
    public static class ProductInfos {

        protected List<ProductInfo> productInfo;

        /**
         * Gets the value of the productInfo property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the productInfo property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProductInfo().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo }
         *
         *
         */
        public List<ProductInfo> getProductInfo() {
            if (productInfo == null) {
                productInfo = new ArrayList<ProductInfo>();
            }
            return this.productInfo;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="baseInfo">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="resourceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="sights">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="sight" maxOccurs="unbounded">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="sightName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="productName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="bookConfig">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="paymentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="advanceOption">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="bookAdvanceDay" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="bookAdvanceTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="useAdvanceHour" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="autoCancelTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="bookPersonType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="visitPersonRequiredForQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="priceConfig">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="validType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="daysAfterUseDateValid" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="calendarPrices" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="calendarPrice" maxOccurs="unbounded">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="useDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="marketPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="sellPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="sellstock" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="productDescription">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="remind" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="refundOption">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="canRefund" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="refundApplyTimeBeforeValidEndDay" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="refundCharge" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="refundInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="otherConfig">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="smsTemplet" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="eticketType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "baseInfo",
            "bookConfig",
            "priceConfig",
            "productDescription",
            "otherConfig"
        })
        public static class ProductInfo {

            @XmlElement(required = true)
            protected GetProductByOTAResponseBody.ProductInfos.ProductInfo.BaseInfo baseInfo;
            @XmlElement(required = true)
            protected GetProductByOTAResponseBody.ProductInfos.ProductInfo.BookConfig bookConfig;
            @XmlElement(required = true)
            protected GetProductByOTAResponseBody.ProductInfos.ProductInfo.PriceConfig priceConfig;
            @XmlElement(required = true)
            protected GetProductByOTAResponseBody.ProductInfos.ProductInfo.ProductDescription productDescription;
            @XmlElement(required = true)
            protected GetProductByOTAResponseBody.ProductInfos.ProductInfo.OtherConfig otherConfig;

            /**
             * Gets the value of the baseInfo property.
             *
             * @return
             *     possible object is
             *     {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.BaseInfo }
             *
             */
            public GetProductByOTAResponseBody.ProductInfos.ProductInfo.BaseInfo getBaseInfo() {
                return baseInfo;
            }

            /**
             * Sets the value of the baseInfo property.
             *
             * @param value
             *     allowed object is
             *     {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.BaseInfo }
             *
             */
            public void setBaseInfo(GetProductByOTAResponseBody.ProductInfos.ProductInfo.BaseInfo value) {
                this.baseInfo = value;
            }

            /**
             * Gets the value of the bookConfig property.
             *
             * @return
             *     possible object is
             *     {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.BookConfig }
             *
             */
            public GetProductByOTAResponseBody.ProductInfos.ProductInfo.BookConfig getBookConfig() {
                return bookConfig;
            }

            /**
             * Sets the value of the bookConfig property.
             *
             * @param value
             *     allowed object is
             *     {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.BookConfig }
             *
             */
            public void setBookConfig(GetProductByOTAResponseBody.ProductInfos.ProductInfo.BookConfig value) {
                this.bookConfig = value;
            }

            /**
             * Gets the value of the priceConfig property.
             *
             * @return
             *     possible object is
             *     {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.PriceConfig }
             *
             */
            public GetProductByOTAResponseBody.ProductInfos.ProductInfo.PriceConfig getPriceConfig() {
                return priceConfig;
            }

            /**
             * Sets the value of the priceConfig property.
             *
             * @param value
             *     allowed object is
             *     {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.PriceConfig }
             *
             */
            public void setPriceConfig(GetProductByOTAResponseBody.ProductInfos.ProductInfo.PriceConfig value) {
                this.priceConfig = value;
            }

            /**
             * Gets the value of the productDescription property.
             *
             * @return
             *     possible object is
             *     {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.ProductDescription }
             *
             */
            public GetProductByOTAResponseBody.ProductInfos.ProductInfo.ProductDescription getProductDescription() {
                return productDescription;
            }

            /**
             * Sets the value of the productDescription property.
             *
             * @param value
             *     allowed object is
             *     {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.ProductDescription }
             *
             */
            public void setProductDescription(GetProductByOTAResponseBody.ProductInfos.ProductInfo.ProductDescription value) {
                this.productDescription = value;
            }

            /**
             * Gets the value of the otherConfig property.
             *
             * @return
             *     possible object is
             *     {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.OtherConfig }
             *
             */
            public GetProductByOTAResponseBody.ProductInfos.ProductInfo.OtherConfig getOtherConfig() {
                return otherConfig;
            }

            /**
             * Sets the value of the otherConfig property.
             *
             * @param value
             *     allowed object is
             *     {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.OtherConfig }
             *
             */
            public void setOtherConfig(GetProductByOTAResponseBody.ProductInfos.ProductInfo.OtherConfig value) {
                this.otherConfig = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="resourceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="sights">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="sight" maxOccurs="unbounded">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="sightName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="productName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "resourceId",
                "sights",
                "productName"
            })
            public static class BaseInfo {

                @XmlElement(required = true)
                protected String resourceId;
                @XmlElement(required = true)
                protected GetProductByOTAResponseBody.ProductInfos.ProductInfo.BaseInfo.Sights sights;
                @XmlElement(required = true)
                protected String productName;

                /**
                 * Gets the value of the resourceId property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getResourceId() {
                    return resourceId;
                }

                /**
                 * Sets the value of the resourceId property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setResourceId(String value) {
                    this.resourceId = value;
                }

                /**
                 * Gets the value of the sights property.
                 *
                 * @return
                 *     possible object is
                 *     {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.BaseInfo.Sights }
                 *
                 */
                public GetProductByOTAResponseBody.ProductInfos.ProductInfo.BaseInfo.Sights getSights() {
                    return sights;
                }

                /**
                 * Sets the value of the sights property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.BaseInfo.Sights }
                 *
                 */
                public void setSights(GetProductByOTAResponseBody.ProductInfos.ProductInfo.BaseInfo.Sights value) {
                    this.sights = value;
                }

                /**
                 * Gets the value of the productName property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getProductName() {
                    return productName;
                }

                /**
                 * Sets the value of the productName property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setProductName(String value) {
                    this.productName = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 *
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 *
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="sight" maxOccurs="unbounded">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="sightName" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 *
                 *
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "sight"
                })
                public static class Sights {

                    @XmlElement(required = true)
                    protected List<Sight> sight;

                    /**
                     * Gets the value of the sight property.
                     *
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the sight property.
                     *
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getSight().add(newItem);
                     * </pre>
                     *
                     *
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.BaseInfo.Sights.Sight }
                     *
                     *
                     */
                    public List<Sight> getSight() {
                        if (sight == null) {
                            sight = new ArrayList<Sight>();
                        }
                        return this.sight;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     *
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     *
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="sightName" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     *
                     *
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "sightName",
                        "city"
                    })
                    public static class Sight {

                        @XmlElement(required = true)
                        protected String sightName;
                        @XmlElement(required = true)
                        protected String city;

                        /**
                         * Gets the value of the sightName property.
                         *
                         * @return
                         *     possible object is
                         *     {@link String }
                         *
                         */
                        public String getSightName() {
                            return sightName;
                        }

                        /**
                         * Sets the value of the sightName property.
                         *
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *
                         */
                        public void setSightName(String value) {
                            this.sightName = value;
                        }

                        /**
                         * Gets the value of the city property.
                         *
                         * @return
                         *     possible object is
                         *     {@link String }
                         *
                         */
                        public String getCity() {
                            return city;
                        }

                        /**
                         * Sets the value of the city property.
                         *
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *
                         */
                        public void setCity(String value) {
                            this.city = value;
                        }

                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="paymentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="advanceOption">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="bookAdvanceDay" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="bookAdvanceTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="useAdvanceHour" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="autoCancelTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="bookPersonType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="visitPersonRequiredForQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "paymentType",
                "advanceOption",
                "autoCancelTime",
                "bookPersonType",
                "visitPersonRequiredForQuantity"
            })
            public static class BookConfig {

                @XmlElement(required = true)
                protected String paymentType;
                @XmlElement(required = true)
                protected GetProductByOTAResponseBody.ProductInfos.ProductInfo.BookConfig.AdvanceOption advanceOption;
                @XmlElement(required = true)
                protected String autoCancelTime;
                @XmlElement(required = true)
                protected String bookPersonType;
                @XmlElement(required = true)
                protected String visitPersonRequiredForQuantity;

                /**
                 * Gets the value of the paymentType property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getPaymentType() {
                    return paymentType;
                }

                /**
                 * Sets the value of the paymentType property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setPaymentType(String value) {
                    this.paymentType = value;
                }

                /**
                 * Gets the value of the advanceOption property.
                 *
                 * @return
                 *     possible object is
                 *     {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.BookConfig.AdvanceOption }
                 *
                 */
                public GetProductByOTAResponseBody.ProductInfos.ProductInfo.BookConfig.AdvanceOption getAdvanceOption() {
                    return advanceOption;
                }

                /**
                 * Sets the value of the advanceOption property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.BookConfig.AdvanceOption }
                 *
                 */
                public void setAdvanceOption(GetProductByOTAResponseBody.ProductInfos.ProductInfo.BookConfig.AdvanceOption value) {
                    this.advanceOption = value;
                }

                /**
                 * Gets the value of the autoCancelTime property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getAutoCancelTime() {
                    return autoCancelTime;
                }

                /**
                 * Sets the value of the autoCancelTime property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setAutoCancelTime(String value) {
                    this.autoCancelTime = value;
                }

                /**
                 * Gets the value of the bookPersonType property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getBookPersonType() {
                    return bookPersonType;
                }

                /**
                 * Sets the value of the bookPersonType property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setBookPersonType(String value) {
                    this.bookPersonType = value;
                }

                /**
                 * Gets the value of the visitPersonRequiredForQuantity property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getVisitPersonRequiredForQuantity() {
                    return visitPersonRequiredForQuantity;
                }

                /**
                 * Sets the value of the visitPersonRequiredForQuantity property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setVisitPersonRequiredForQuantity(String value) {
                    this.visitPersonRequiredForQuantity = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 *
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 *
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="bookAdvanceDay" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="bookAdvanceTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="useAdvanceHour" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 *
                 *
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "bookAdvanceDay",
                    "bookAdvanceTime",
                    "useAdvanceHour"
                })
                public static class AdvanceOption {

                    @XmlElement(required = true, defaultValue = "0")
                    protected String bookAdvanceDay;
                    @XmlElement(required = true)
                    protected String bookAdvanceTime;
                    @XmlElement(required = true)
                    protected String useAdvanceHour;

                    /**
                     * Gets the value of the bookAdvanceDay property.
                     *
                     * @return
                     *     possible object is
                     *     {@link String }
                     *
                     */
                    public String getBookAdvanceDay() {
                        return bookAdvanceDay;
                    }

                    /**
                     * Sets the value of the bookAdvanceDay property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *
                     */
                    public void setBookAdvanceDay(String value) {
                        this.bookAdvanceDay = value;
                    }

                    /**
                     * Gets the value of the bookAdvanceTime property.
                     *
                     * @return
                     *     possible object is
                     *     {@link String }
                     *
                     */
                    public String getBookAdvanceTime() {
                        return bookAdvanceTime;
                    }

                    /**
                     * Sets the value of the bookAdvanceTime property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *
                     */
                    public void setBookAdvanceTime(String value) {
                        this.bookAdvanceTime = value;
                    }

                    /**
                     * Gets the value of the useAdvanceHour property.
                     *
                     * @return
                     *     possible object is
                     *     {@link String }
                     *
                     */
                    public String getUseAdvanceHour() {
                        return useAdvanceHour;
                    }

                    /**
                     * Sets the value of the useAdvanceHour property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *
                     */
                    public void setUseAdvanceHour(String value) {
                        this.useAdvanceHour = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="smsTemplet" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="eticketType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "smsTemplet",
                "eticketType"
            })
            public static class OtherConfig {

                @XmlElement(required = true)
                protected String smsTemplet;
                @XmlElement(required = true)
                protected String eticketType;

                /**
                 * Gets the value of the smsTemplet property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getSmsTemplet() {
                    return smsTemplet;
                }

                /**
                 * Sets the value of the smsTemplet property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setSmsTemplet(String value) {
                    this.smsTemplet = value;
                }

                /**
                 * Gets the value of the eticketType property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getEticketType() {
                    return eticketType;
                }

                /**
                 * Sets the value of the eticketType property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setEticketType(String value) {
                    this.eticketType = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="validType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="daysAfterUseDateValid" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="calendarPrices" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="calendarPrice" maxOccurs="unbounded">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="useDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="marketPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="sellPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="sellstock" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "validType",
                "daysAfterUseDateValid",
                "calendarPrices"
            })
            public static class PriceConfig {

                @XmlElement(required = true)
                protected String validType;
                @XmlElement(required = true)
                protected String daysAfterUseDateValid;
                protected GetProductByOTAResponseBody.ProductInfos.ProductInfo.PriceConfig.CalendarPrices calendarPrices;

                /**
                 * Gets the value of the validType property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getValidType() {
                    return validType;
                }

                /**
                 * Sets the value of the validType property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setValidType(String value) {
                    this.validType = value;
                }

                /**
                 * Gets the value of the daysAfterUseDateValid property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getDaysAfterUseDateValid() {
                    return daysAfterUseDateValid;
                }

                /**
                 * Sets the value of the daysAfterUseDateValid property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setDaysAfterUseDateValid(String value) {
                    this.daysAfterUseDateValid = value;
                }

                /**
                 * Gets the value of the calendarPrices property.
                 *
                 * @return
                 *     possible object is
                 *     {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.PriceConfig.CalendarPrices }
                 *
                 */
                public GetProductByOTAResponseBody.ProductInfos.ProductInfo.PriceConfig.CalendarPrices getCalendarPrices() {
                    return calendarPrices;
                }

                /**
                 * Sets the value of the calendarPrices property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.PriceConfig.CalendarPrices }
                 *
                 */
                public void setCalendarPrices(GetProductByOTAResponseBody.ProductInfos.ProductInfo.PriceConfig.CalendarPrices value) {
                    this.calendarPrices = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 *
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 *
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="calendarPrice" maxOccurs="unbounded">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="useDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="marketPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="sellPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="sellstock" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 *
                 *
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "calendarPrice"
                })
                public static class CalendarPrices {

                    @XmlElement(required = true)
                    protected List<CalendarPrice> calendarPrice;

                    /**
                     * Gets the value of the calendarPrice property.
                     *
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the calendarPrice property.
                     *
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getCalendarPrice().add(newItem);
                     * </pre>
                     *
                     *
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.PriceConfig.CalendarPrices.CalendarPrice }
                     *
                     *
                     */
                    public List<CalendarPrice> getCalendarPrice() {
                        if (calendarPrice == null) {
                            calendarPrice = new ArrayList<CalendarPrice>();
                        }
                        return this.calendarPrice;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     *
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     *
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="useDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="marketPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="sellPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="sellstock" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     *
                     *
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "useDate",
                        "marketPrice",
                        "sellPrice",
                        "sellstock"
                    })
                    public static class CalendarPrice {

                        @XmlElement(required = true)
                        protected String useDate;
                        @XmlElement(required = true)
                        protected String marketPrice;
                        @XmlElement(required = true)
                        protected String sellPrice;
                        @XmlElement(required = true)
                        protected String sellstock;

                        /**
                         * Gets the value of the useDate property.
                         *
                         * @return
                         *     possible object is
                         *     {@link String }
                         *
                         */
                        public String getUseDate() {
                            return useDate;
                        }

                        /**
                         * Sets the value of the useDate property.
                         *
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *
                         */
                        public void setUseDate(String value) {
                            this.useDate = value;
                        }

                        /**
                         * Gets the value of the marketPrice property.
                         *
                         * @return
                         *     possible object is
                         *     {@link String }
                         *
                         */
                        public String getMarketPrice() {
                            return marketPrice;
                        }

                        /**
                         * Sets the value of the marketPrice property.
                         *
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *
                         */
                        public void setMarketPrice(String value) {
                            this.marketPrice = value;
                        }

                        /**
                         * Gets the value of the sellPrice property.
                         *
                         * @return
                         *     possible object is
                         *     {@link String }
                         *
                         */
                        public String getSellPrice() {
                            return sellPrice;
                        }

                        /**
                         * Sets the value of the sellPrice property.
                         *
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *
                         */
                        public void setSellPrice(String value) {
                            this.sellPrice = value;
                        }

                        /**
                         * Gets the value of the sellstock property.
                         *
                         * @return
                         *     possible object is
                         *     {@link String }
                         *
                         */
                        public String getSellstock() {
                            return sellstock;
                        }

                        /**
                         * Sets the value of the sellstock property.
                         *
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *
                         */
                        public void setSellstock(String value) {
                            this.sellstock = value;
                        }

                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="remind" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="refundOption">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="canRefund" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="refundApplyTimeBeforeValidEndDay" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="refundCharge" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="refundInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "remind",
                "refundOption"
            })
            public static class ProductDescription {

                @XmlElement(required = true)
                protected String remind;
                @XmlElement(required = true)
                protected GetProductByOTAResponseBody.ProductInfos.ProductInfo.ProductDescription.RefundOption refundOption;

                /**
                 * Gets the value of the remind property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getRemind() {
                    return remind;
                }

                /**
                 * Sets the value of the remind property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setRemind(String value) {
                    this.remind = value;
                }

                /**
                 * Gets the value of the refundOption property.
                 *
                 * @return
                 *     possible object is
                 *     {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.ProductDescription.RefundOption }
                 *
                 */
                public GetProductByOTAResponseBody.ProductInfos.ProductInfo.ProductDescription.RefundOption getRefundOption() {
                    return refundOption;
                }

                /**
                 * Sets the value of the refundOption property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.ProductDescription.RefundOption }
                 *
                 */
                public void setRefundOption(GetProductByOTAResponseBody.ProductInfos.ProductInfo.ProductDescription.RefundOption value) {
                    this.refundOption = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="canRefund" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="refundApplyTimeBeforeValidEndDay" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="refundCharge" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="refundInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "canRefund",
                    "refundApplyTimeBeforeValidEndDay",
                    "refundCharge",
                    "refundInfo"
                })
                public static class RefundOption {

                    @XmlElement(required = true)
                    protected String canRefund;
                    @XmlElement(required = true)
                    protected String refundApplyTimeBeforeValidEndDay;
                    @XmlElement(required = true)
                    protected String refundCharge;
                    @XmlElement(required = true)
                    protected String refundInfo;

                    /**
                     * Gets the value of the canRefund property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getCanRefund() {
                        return canRefund;
                    }

                    /**
                     * Sets the value of the canRefund property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setCanRefund(String value) {
                        this.canRefund = value;
                    }

                    /**
                     * Gets the value of the refundApplyTimeBeforeValidEndDay property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getRefundApplyTimeBeforeValidEndDay() {
                        return refundApplyTimeBeforeValidEndDay;
                    }

                    /**
                     * Sets the value of the refundApplyTimeBeforeValidEndDay property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setRefundApplyTimeBeforeValidEndDay(String value) {
                        this.refundApplyTimeBeforeValidEndDay = value;
                    }

                    /**
                     * Gets the value of the refundCharge property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getRefundCharge() {
                        return refundCharge;
                    }

                    /**
                     * Sets the value of the refundCharge property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setRefundCharge(String value) {
                        this.refundCharge = value;
                    }

                    /**
                     * Gets the value of the refundInfo property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getRefundInfo() {
                        return refundInfo;
                    }

                    /**
                     * Sets the value of the refundInfo property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setRefundInfo(String value) {
                        this.refundInfo = value;
                    }

                }

            }

        }

    }

}
