//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.25 at 03:35:49 ���� CST 
//


package com.lvmama.passport.processor.impl.client.jiuwang.model.v1.response;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ectrip.tour._2014.qmresponseschema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ectrip.tour._2014.qmresponseschema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo }
     * 
     */
    public GetProductByOTAResponseBody.ProductInfos.ProductInfo createGetProductByOTAResponseBodyProductInfosProductInfo() {
        return new GetProductByOTAResponseBody.ProductInfos.ProductInfo();
    }

    /**
     * Create an instance of {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.BookConfig }
     * 
     */
    public GetProductByOTAResponseBody.ProductInfos.ProductInfo.BookConfig createGetProductByOTAResponseBodyProductInfosProductInfoBookConfig() {
        return new GetProductByOTAResponseBody.ProductInfos.ProductInfo.BookConfig();
    }

    /**
     * Create an instance of {@link GetProductByOTAResponseBody.ProductInfos }
     * 
     */
    public GetProductByOTAResponseBody.ProductInfos createGetProductByOTAResponseBodyProductInfos() {
        return new GetProductByOTAResponseBody.ProductInfos();
    }

    /**
     * Create an instance of {@link CreateOrderResponseBody.OrderInfo }
     * 
     */
    public CreateOrderResponseBody.OrderInfo createCreateOrderResponseBodyOrderInfo() {
        return new CreateOrderResponseBody.OrderInfo();
    }

    /**
     * Create an instance of {@link PayOrderResponseBody.OrderInfo }
     * 
     */
    public PayOrderResponseBody.OrderInfo createPayOrderResponseBodyOrderInfo() {
        return new PayOrderResponseBody.OrderInfo();
    }

    /**
     * Create an instance of {@link ResponseHeader }
     * 
     */
    public ResponseHeader createResponseHeader() {
        return new ResponseHeader();
    }

    /**
     * Create an instance of {@link PushOrderResponseBody }
     * 
     */
    public PushOrderResponseBody createPushOrderResponseBody() {
        return new PushOrderResponseBody();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.PriceConfig.CalendarPrices.CalendarPrice }
     * 
     */
    public GetProductByOTAResponseBody.ProductInfos.ProductInfo.PriceConfig.CalendarPrices.CalendarPrice createGetProductByOTAResponseBodyProductInfosProductInfoPriceConfigCalendarPricesCalendarPrice() {
        return new GetProductByOTAResponseBody.ProductInfos.ProductInfo.PriceConfig.CalendarPrices.CalendarPrice();
    }

    /**
     * Create an instance of {@link ResponseBody }
     * 
     */
    public ResponseBody createResponseBody() {
        return new ResponseBody();
    }

    /**
     * Create an instance of {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.ProductDescription }
     * 
     */
    public GetProductByOTAResponseBody.ProductInfos.ProductInfo.ProductDescription createGetProductByOTAResponseBodyProductInfosProductInfoProductDescription() {
        return new GetProductByOTAResponseBody.ProductInfos.ProductInfo.ProductDescription();
    }

    /**
     * Create an instance of {@link CreateOrderResponseBody }
     * 
     */
    public CreateOrderResponseBody createCreateOrderResponseBody() {
        return new CreateOrderResponseBody();
    }

    /**
     * Create an instance of {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.BaseInfo }
     * 
     */
    public GetProductByOTAResponseBody.ProductInfos.ProductInfo.BaseInfo createGetProductByOTAResponseBodyProductInfosProductInfoBaseInfo() {
        return new GetProductByOTAResponseBody.ProductInfos.ProductInfo.BaseInfo();
    }

    /**
     * Create an instance of {@link ApplyOrderRefundByUserResponseBody }
     * 
     */
    public ApplyOrderRefundByUserResponseBody createApplyOrderRefundByUserResponseBody() {
        return new ApplyOrderRefundByUserResponseBody();
    }

    /**
     * Create an instance of {@link NoticeProductChangedResponseBody }
     * 
     */
    public NoticeProductChangedResponseBody createNoticeProductChangedResponseBody() {
        return new NoticeProductChangedResponseBody();
    }

    /**
     * Create an instance of {@link GetProductByOTAResponseBody }
     * 
     */
    public GetProductByOTAResponseBody createGetProductByOTAResponseBody() {
        return new GetProductByOTAResponseBody();
    }

    /**
     * Create an instance of {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.PriceConfig.CalendarPrices }
     * 
     */
    public GetProductByOTAResponseBody.ProductInfos.ProductInfo.PriceConfig.CalendarPrices createGetProductByOTAResponseBodyProductInfosProductInfoPriceConfigCalendarPrices() {
        return new GetProductByOTAResponseBody.ProductInfos.ProductInfo.PriceConfig.CalendarPrices();
    }

    /**
     * Create an instance of {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.BaseInfo.Sights.Sight }
     * 
     */
    public GetProductByOTAResponseBody.ProductInfos.ProductInfo.BaseInfo.Sights.Sight createGetProductByOTAResponseBodyProductInfosProductInfoBaseInfoSightsSight() {
        return new GetProductByOTAResponseBody.ProductInfos.ProductInfo.BaseInfo.Sights.Sight();
    }

    /**
     * Create an instance of {@link PushOrderResponseBody.OrderInfo }
     * 
     */
    public PushOrderResponseBody.OrderInfo createPushOrderResponseBodyOrderInfo() {
        return new PushOrderResponseBody.OrderInfo();
    }

    /**
     * Create an instance of {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.PriceConfig }
     * 
     */
    public GetProductByOTAResponseBody.ProductInfos.ProductInfo.PriceConfig createGetProductByOTAResponseBodyProductInfosProductInfoPriceConfig() {
        return new GetProductByOTAResponseBody.ProductInfos.ProductInfo.PriceConfig();
    }

    /**
     * Create an instance of {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.BaseInfo.Sights }
     * 
     */
    public GetProductByOTAResponseBody.ProductInfos.ProductInfo.BaseInfo.Sights createGetProductByOTAResponseBodyProductInfosProductInfoBaseInfoSights() {
        return new GetProductByOTAResponseBody.ProductInfos.ProductInfo.BaseInfo.Sights();
    }

    /**
     * Create an instance of {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.OtherConfig }
     * 
     */
    public GetProductByOTAResponseBody.ProductInfos.ProductInfo.OtherConfig createGetProductByOTAResponseBodyProductInfosProductInfoOtherConfig() {
        return new GetProductByOTAResponseBody.ProductInfos.ProductInfo.OtherConfig();
    }

    /**
     * Create an instance of {@link GetOrderByOTAResponseBody.OrderInfo }
     * 
     */
    public GetOrderByOTAResponseBody.OrderInfo createGetOrderByOTAResponseBodyOrderInfo() {
        return new GetOrderByOTAResponseBody.OrderInfo();
    }

    /**
     * Create an instance of {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.ProductDescription.RefundOption }
     * 
     */
    public GetProductByOTAResponseBody.ProductInfos.ProductInfo.ProductDescription.RefundOption createGetProductByOTAResponseBodyProductInfosProductInfoProductDescriptionRefundOption() {
        return new GetProductByOTAResponseBody.ProductInfos.ProductInfo.ProductDescription.RefundOption();
    }

    /**
     * Create an instance of {@link GetOrderByOTAResponseBody }
     * 
     */
    public GetOrderByOTAResponseBody createGetOrderByOTAResponseBody() {
        return new GetOrderByOTAResponseBody();
    }

    /**
     * Create an instance of {@link NoticeOrderRefundApproveResultResponseBody }
     * 
     */
    public NoticeOrderRefundApproveResultResponseBody createNoticeOrderRefundApproveResultResponseBody() {
        return new NoticeOrderRefundApproveResultResponseBody();
    }

    /**
     * Create an instance of {@link NoticeOrderRefundedByOTAResponseBody }
     * 
     */
    public NoticeOrderRefundedByOTAResponseBody createNoticeOrderRefundedByOTAResponseBody() {
        return new NoticeOrderRefundedByOTAResponseBody();
    }

    /**
     * Create an instance of {@link SendOrderEticketResponseBody }
     * 
     */
    public SendOrderEticketResponseBody createSendOrderEticketResponseBody() {
        return new SendOrderEticketResponseBody();
    }

    /**
     * Create an instance of {@link PayOrderResponseBody }
     * 
     */
    public PayOrderResponseBody createPayOrderResponseBody() {
        return new PayOrderResponseBody();
    }

    /**
     * Create an instance of {@link NoticeOrderConsumedResponseBody }
     * 
     */
    public NoticeOrderConsumedResponseBody createNoticeOrderConsumedResponseBody() {
        return new NoticeOrderConsumedResponseBody();
    }

    /**
     * Create an instance of {@link NoticeOrderEticketSendedResponseBody }
     * 
     */
    public NoticeOrderEticketSendedResponseBody createNoticeOrderEticketSendedResponseBody() {
        return new NoticeOrderEticketSendedResponseBody();
    }

    /**
     * Create an instance of {@link GetProductByOTAResponseBody.ProductInfos.ProductInfo.BookConfig.AdvanceOption }
     * 
     */
    public GetProductByOTAResponseBody.ProductInfos.ProductInfo.BookConfig.AdvanceOption createGetProductByOTAResponseBodyProductInfosProductInfoBookConfigAdvanceOption() {
        return new GetProductByOTAResponseBody.ProductInfos.ProductInfo.BookConfig.AdvanceOption();
    }

}
