//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.25 at 03:35:49 ���� CST 
//


package com.lvmama.passport.processor.impl.client.jiuwang.model.v1.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 门票数据体基类
 *
 * <p>Java class for ResponseBody complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ResponseBody">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseBody")
@XmlSeeAlso({
        NoticeOrderRefundedByOTAResponseBody.class,
        NoticeOrderRefundApproveResultResponseBody.class,
        NoticeProductChangedResponseBody.class,
        NoticeOrderConsumedResponseBody.class,
        SendOrderEticketResponseBody.class,
        CreatePaymentOrderResponseBody.class,
        PayOrderResponseBody.class,
        GetOrderByOTAResponseBody.class,
        GetProductByOTAResponseBody.class,
        CreateOrderResponseBody.class,
        ApplyOrderRefundByUserResponseBody.class,
        PushOrderResponseBody.class,
        NoticeOrderEticketSendedResponseBody.class
})
public class ResponseBody {


}
