package com.lvmama.sms.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import net.sf.json.JSONSerializer;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import com.lvmama.comm.BaseIbatisDAO;
import com.lvmama.comm.pet.po.pub.ComSmsTemplate;
import com.lvmama.comm.spring.SpringBeanProxy;

public class ComSmsTemplateDAO extends BaseIbatisDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table COM_SMS_TEMPLATE
	 * 
	 * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
	 */
	public int deleteByPrimaryKey(String templateId) {
		ComSmsTemplate key = new ComSmsTemplate();
		key.setTemplateId(templateId);
		int rows = super.delete(
				"COM_SMS_TEMPLATE.deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table COM_SMS_TEMPLATE
	 * 
	 * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
	 */
	public void insert(ComSmsTemplate record) {
		super.insert(
				"COM_SMS_TEMPLATE.insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table COM_SMS_TEMPLATE
	 * 
	 * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
	 */
	public ComSmsTemplate selectByPrimaryKey(String templateId)
			 {
		ComSmsTemplate key = new ComSmsTemplate();
		key.setTemplateId(templateId);
		ComSmsTemplate record = (ComSmsTemplate) super
				.queryForObject(
						"COM_SMS_TEMPLATE.selectByPrimaryKey",
						key);
		return record;
	}
	
	
	public static void main(String[] args) {
		ApplicationContext context = new ClassPathXmlApplicationContext("applicationContext-order-beans.xml");
		System.out.println(context.getBeanDefinitionCount());
		ComSmsTemplateDAO comSmsTemplateDAO = (ComSmsTemplateDAO)context.getBean("comSmsTemplateDAO");
		System.out.println(JSONSerializer.toJSON(comSmsTemplateDAO.selectAllTemplate().get(0)));
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table COM_SMS_TEMPLATE
	 * 
	 * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
	 */
	public int updateByPrimaryKey(ComSmsTemplate record) {
		int rows = super.update(
				"COM_SMS_TEMPLATE.updateByPrimaryKey", record);
		return rows;
	}
	
	
	public List<ComSmsTemplate> selectAllTemplate() {
		Map<String, Object> paramsMap=new HashMap<String, Object>();
		paramsMap.put("templateType", null);
		return super.queryForList("COM_SMS_TEMPLATE.selectAll",paramsMap);
	}
	
	/**
	 * 查询指定类别短信
	 * @param templateType 模板类型 @see com.lvmama.comm.vo.Constant.SMS_TEMPLATE_TYPE
	 * @return
	 */
	public List<ComSmsTemplate> selectAllTemplate(String templateType){
		Map<String, Object> paramsMap=new HashMap<String, Object>();
		paramsMap.put("templateType", templateType);
		return super.queryForList("COM_SMS_TEMPLATE.selectAll",paramsMap);
	}
	
	/**
	 * 根据参数查询短信模板信息
	 * */
	@SuppressWarnings("unchecked")
	public List<ComSmsTemplate> getListByParams(Map<String, Object> params){
		return super.queryForList("COM_SMS_TEMPLATE.getListByParams", params);
	}
	
	/**
	 * 根据参数查询所有的短信模板数量
	 * */
	public Long getListCountByParams(Map<String, Object> params){
		return Long.valueOf(super.queryForObject("COM_SMS_TEMPLATE.getListCountByParams",params).toString());
	}

}