package com.lvmama.comm.pet.po.pub;

import java.io.Serializable;

public class ComContactRelation implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 2459687126896172540L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM_CONTACT_RELATION.CONTACT_RELATION_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private Long contactRelationId;
    
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM_CONTACT_RELATION.CONTACT_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private Long contactId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM_CONTACT_RELATION.OBJECT_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private Long objectId;
    
    private String objectType;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM_CONTACT_RELATION.CONTACT_RELATION_ID
     *
     * @return the value of COM_CONTACT_RELATION.CONTACT_RELATION_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public Long getContactRelationId() {
        return contactRelationId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM_CONTACT_RELATION.CONTACT_RELATION_ID
     *
     * @param contactRelationId the value for COM_CONTACT_RELATION.CONTACT_RELATION_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setContactRelationId(Long contactRelationId) {
        this.contactRelationId = contactRelationId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM_CONTACT_RELATION.CONTACT_ID
     *
     * @return the value of COM_CONTACT_RELATION.CONTACT_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public Long getContactId() {
        return contactId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM_CONTACT_RELATION.CONTACT_ID
     *
     * @param contactId the value for COM_CONTACT_RELATION.CONTACT_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setContactId(Long contactId) {
        this.contactId = contactId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM_CONTACT_RELATION.OBJECT_ID
     *
     * @return the value of COM_CONTACT_RELATION.OBJECT_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public Long getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM_CONTACT_RELATION.OBJECT_ID
     *
     * @param objectId the value for COM_CONTACT_RELATION.OBJECT_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setObjectId(Long objectId) {
        this.objectId = objectId;
    }

	public String getObjectType() {
		return objectType;
	}

	public void setObjectType(String objectType) {
		this.objectType = objectType;
	}
}