package com.lvmama.comm.pet.po.pub;

import java.io.Serializable;

public class ComProvince implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1458541424495375536L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM_PROVINCE.PROVINCE_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private String provinceId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM_PROVINCE.PROVINCE_NAME
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private String provinceName;

    private String checked;
    
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM_PROVINCE.PROVINCE_ID
     *
     * @return the value of COM_PROVINCE.PROVINCE_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public String getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM_PROVINCE.PROVINCE_ID
     *
     * @param provinceId the value for COM_PROVINCE.PROVINCE_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM_PROVINCE.PROVINCE_NAME
     *
     * @return the value of COM_PROVINCE.PROVINCE_NAME
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM_PROVINCE.PROVINCE_NAME
     *
     * @param provinceName the value for COM_PROVINCE.PROVINCE_NAME
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

	public String getChecked() {
		return checked;
	}

	public void setChecked(String checked) {
		this.checked = checked;
	}
}