package com.lvmama.comm.pet.po.pub;

import java.io.Serializable;
import java.util.Date;

public class ComSmsTemplate implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 8680598079531240296L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM_SMS_TEMPLATE.TEMPLATE_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private String templateId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM_SMS_TEMPLATE.TEMPLATE_NAME
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private String templateName;
    
    /**
     * 模板类型
     *	@see com.lvmama.comm.vo.Constant.SMS_TEMPLATE_TYPE
     */
    private String templateType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COM_SMS_TEMPLATE.CONTENT
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    private String content;
    private String immendiately;
    
    private Long channelId;
    
    private String channelType;
    
    private String valid;
    
    /**
     * 指定是否同步更新产品销售渠道相关短信模板信息
     */
    private boolean isModifyProdChannelSms = false;
    
    private Date createTime;
    private String channel;
    private String channelCMCC;
    private String channelCUC;
    private String channelCT;
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM_SMS_TEMPLATE.TEMPLATE_ID
     *
     * @return the value of COM_SMS_TEMPLATE.TEMPLATE_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM_SMS_TEMPLATE.TEMPLATE_ID
     *
     * @param templateId the value for COM_SMS_TEMPLATE.TEMPLATE_ID
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setTemplateId(String templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM_SMS_TEMPLATE.TEMPLATE_NAME
     *
     * @return the value of COM_SMS_TEMPLATE.TEMPLATE_NAME
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM_SMS_TEMPLATE.TEMPLATE_NAME
     *
     * @param templateName the value for COM_SMS_TEMPLATE.TEMPLATE_NAME
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COM_SMS_TEMPLATE.CONTENT
     *
     * @return the value of COM_SMS_TEMPLATE.CONTENT
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COM_SMS_TEMPLATE.CONTENT
     *
     * @param content the value for COM_SMS_TEMPLATE.CONTENT
     *
     * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
     */
    public void setContent(String content) {
        this.content = content;
    }

	public String getImmendiately() {
		return immendiately;
	}

	public void setImmendiately(String immendiately) {
		this.immendiately = immendiately;
	}

	public Long getChannelId() {
		return channelId;
	}

	public void setChannelId(Long channelId) {
		this.channelId = channelId;
	}

	public String getChannelType() {
		return channelType;
	}

	public void setChannelType(String channelType) {
		this.channelType = channelType;
	}

	public String getValid() {
		return valid;
	}

	public void setValid(String valid) {
		this.valid = valid;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getTemplateType() {
		return templateType;
	}

	public void setTemplateType(String templateType) {
		this.templateType = templateType;
	}

	public String getChannel() {
		return channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	public String getChannelCMCC() {
		return channelCMCC;
	}

	public void setChannelCMCC(String channelCMCC) {
		this.channelCMCC = channelCMCC;
	}

	public String getChannelCUC() {
		return channelCUC;
	}

	public void setChannelCUC(String channelCUC) {
		this.channelCUC = channelCUC;
	}

	public String getChannelCT() {
		return channelCT;
	}

	public void setChannelCT(String channelCT) {
		this.channelCT = channelCT;
	}

	public boolean isModifyProdChannelSms() {
		return isModifyProdChannelSms;
	}

	public void setModifyProdChannelSms(boolean isModifyProdChannelSms) {
		this.isModifyProdChannelSms = isModifyProdChannelSms;
	}
	
	
}