package com.lvmama.pet.sup.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.lvmama.comm.BaseIbatisDAO;
import com.lvmama.comm.pet.po.sup.MetaSettlement;
import com.lvmama.comm.vo.Constant;
public class MetaSettlementDAO extends BaseIbatisDAO {

	public int deleteByMetaProductIdAndTargetId(MetaSettlement metaSettlement) {
		int rows = super.delete(
				"META_SETTLEMENT.deleteByMetaProductIdAndTargetId", metaSettlement);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table META_SETTLEMENT
	 * 
	 * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
	 */
	public void insertSuperMetaSettlement(MetaSettlement record) {
		record.setBizType(Constant.PRODUCT_BIZ_TYPE.BEE.name());
		super.insert("META_SETTLEMENT.insert",
				record);
	}
	
	public Integer selectSuperByMetaProductId(Long metaProductId){
		Map<String,Object> par=new HashMap<String,Object>();
		par.put("metaProductId", metaProductId);
		par.put("bizType", Constant.PRODUCT_BIZ_TYPE.BEE.name());
		//par.put("targetId", targetId);
		Integer count= (Integer) super.queryForObject("META_SETTLEMENT.selectByMetaProductIdAndTargetId",par);
		return count;
 	}

	public Long selectTargetIdByMetaProductId(Long metaProductId) {
		Map<String,Object> par=new HashMap<String,Object>();
		par.put("metaProductId", metaProductId);
		par.put("bizType", Constant.PRODUCT_BIZ_TYPE.BEE.name());
		return  (Long) super.queryForObject("META_SETTLEMENT.selectTargetIdByMetaProductId",par);
	}
	
	public MetaSettlement findMetaSettlementByMetaProductId(Long metaProductId) {
		Map<String,Object> par=new HashMap<String,Object>();
		par.put("metaProductId", metaProductId);
		par.put("bizType", Constant.PRODUCT_BIZ_TYPE.BEE.name());
		@SuppressWarnings("unchecked")
		List<MetaSettlement> list=super.queryForList("META_SETTLEMENT.findMetaSettlementByMetaProductId", par);
		if(null!=list&&list.size()>0){
			return list.get(0);
		}
		return null;
	}
	
 
}