package com.lvmama.com.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.lvmama.comm.BaseIbatisDAO;
import com.lvmama.comm.bee.po.pub.ComAudit;

public class ComAuditDAO extends BaseIbatisDAO{
	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table COM_AUDIT
	 * 
	 * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
	 */
	public int deleteByPrimaryKey(Long auditId) {
		ComAudit key = new ComAudit();
		key.setAuditId(auditId);
		int rows = super.delete(
				"COM_AUDIT.deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table COM_AUDIT
	 * 
	 * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
	 */
	public void insert(ComAudit record) {
		super.insert("COM_AUDIT.insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table COM_AUDIT
	 * 
	 * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
	 */
	public ComAudit selectByPrimaryKey(Long auditId) {
		ComAudit key = new ComAudit();
		key.setAuditId(auditId);
		ComAudit record = (ComAudit) super.queryForObject(
				"COM_AUDIT.selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table COM_AUDIT
	 * 
	 * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
	 */
	public int updateByPrimaryKey(ComAudit record) {
		int rows = super.update(
				"COM_AUDIT.updateByPrimaryKey", record);
		return rows;
	}
	
	public List<ComAudit> selectByOrderIdAndOperator(Long orderId, String operator){
		Map map = new HashMap();
		map.put("objectId", orderId);
		map.put("operatorName", operator);
		map.put("auditStatus", "AUDIT_GOING");
		map.put("objectType", "ORD_ORDER");
		return super.queryForList("COM_AUDIT.selectByParamMap",map,0,1);
	}

}