/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lvmama_pet_fax_utils_MagickImageInfo */

#ifndef _Included_com_lvmama_pet_fax_utils_MagickImageInfo
#define _Included_com_lvmama_pet_fax_utils_MagickImageInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lvmama_pet_fax_utils_MagickImageInfo
 * Method:    buildTiff
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lvmama_pet_fax_utils_MagickImageInfo_buildHTiff
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_lvmama_pet_fax_utils_MagickImageInfo
 * Method:    buildVTiff
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lvmama_pet_fax_utils_MagickImageInfo_buildVTiff
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
