ALTER TABLE EDM_SUBSCRIBE ADD (TRAVEL_TIME VARCHAR2(500), MUST_WANTED_TRAVEL VARCHAR2(500),CHANNEL VARCHAR2(20));
comment on column EDM_SUBSCRIBE.TRAVEL_TIME
  is '旅游时间段,以,间隔';
comment on column EDM_SUBSCRIBE.MUST_WANTED_TRAVEL
  is '最想去的地方，以,间隔';
comment on column EDM_SUBSCRIBE.CHANNEL
  is '订阅来源:FAST-快速,DETAIL-详细,SPACE-我的驴妈妈,BACKEND:数据库JOB';