package com.lvmama.prd.dao;

import java.util.List;

import com.lvmama.comm.BaseIbatisDAO;
import com.lvmama.comm.bee.po.prod.ProdProductItem;

public class ProdProductItemDAO extends BaseIbatisDAO {
	
	public void insert(ProdProductItem record) {
		super.insert(
				"PROD_PRODUCT_ITEM.insert", record);
	}
	
	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table PROD_PRODUCT_ITEM
	 * 
	 * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
	 */
	public int deleteByPrimaryKey(Long productItemId) {
		ProdProductItem key = new ProdProductItem();
		key.setProductItemId(productItemId);
		int rows = super.delete(
				"PROD_PRODUCT_ITEM.deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table PROD_PRODUCT_ITEM
	 * 
	 * @ibatorgenerated Tue Apr 20 11:55:56 CST 2010
	 */
	public int updateByPrimaryKey(ProdProductItem record) {
		int rows = super.update(
				"PROD_PRODUCT_ITEM.updateByPrimaryKey", record);
		return rows;
	}

	public boolean existsProductItem(Long productId, Long metaProductId) {
		ProdProductItem prodProductItem = new ProdProductItem();
		prodProductItem.setProductId(productId);
		prodProductItem.setMetaProductId(metaProductId);
		Integer cnt=(Integer)super.queryForObject("PROD_PRODUCT_ITEM.exists_flag", prodProductItem);
		if (cnt.intValue()>0){
			return true;
		}
		return false;
	}
	@Deprecated
	public Integer countProductItem(Long productId) {
		return (Integer)super.queryForObject("PROD_PRODUCT_ITEM.countProductItem", productId);
	}

	@SuppressWarnings("unchecked")
	public List<ProdProductItem> selectProductItems(Long productId){
		return super.queryForList("PROD_PRODUCT_ITEM.selectProductItemByPid", productId);
	}

	@SuppressWarnings("unchecked")
	public List<ProdProductItem> selectProductByMetaId(Long productId){
		return super.queryForList("PROD_PRODUCT_ITEM.selectProductByMetaId", productId);
	}
	
	/**
	 * 查找采购产品的销售产品
	 * 
	 * @param metaProductId
	 * @return
	 */
	@SuppressWarnings("unchecked")
	public List<ProdProductItem> selectProdProductByMetaId(Long metaProductId) {
		return super.queryForList("PROD_PRODUCT_ITEM.selectProdProductByMetaId", metaProductId);
	}
	
	public Long getProductNearMarketPrice(Long productId){
		return (Long) super.queryForObject("PROD_PRODUCT_ITEM.selectProdctNearMarcketPrice", productId);
	}

}