//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.25 at 03:35:22 ���� CST 
//


package com.lvmama.passport.processor.impl.client.jiuwang.model.v1.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
* 【OTA提供】【订单】畅游通通知用户申请退款结果（noticeOrderRefundApproveResult）
 * 
 * <p>Java class for NoticeOrderRefundApproveResultRequestBody complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NoticeOrderRefundApproveResultRequestBody">
 *   &lt;complexContent>
 *     &lt;extension base="{http://tour.ectrip.com/2014/QMRequestDataSchema}RequestBody">
 *       &lt;sequence>
 *         &lt;element name="orderInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="partnerorderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="refundSeq" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="orderQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="refundResult" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="refundQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="orderRefundPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="orderRefundCharge" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NoticeOrderRefundApproveResultRequestBody", propOrder = {
    "orderInfo"
})
public class NoticeOrderRefundApproveResultRequestBody
    extends RequestBody
{

    @XmlElement(required = true)
    protected NoticeOrderRefundApproveResultRequestBody.OrderInfo orderInfo;

    /**
     * Gets the value of the orderInfo property.
     *
     * @return
     *     possible object is
     *     {@link NoticeOrderRefundApproveResultRequestBody.OrderInfo }
     *
     */
    public NoticeOrderRefundApproveResultRequestBody.OrderInfo getOrderInfo() {
        return orderInfo;
    }

    /**
     * Sets the value of the orderInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link NoticeOrderRefundApproveResultRequestBody.OrderInfo }
     *
     */
    public void setOrderInfo(NoticeOrderRefundApproveResultRequestBody.OrderInfo value) {
        this.orderInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="partnerorderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="refundSeq" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="orderQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="refundResult" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="refundQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="orderRefundPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="orderRefundCharge" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "partnerorderId",
        "refundSeq",
        "orderQuantity",
        "refundResult",
        "refundQuantity",
        "orderRefundPrice",
        "orderRefundCharge"
    })
    public static class OrderInfo {

        @XmlElement(required = true)
        protected String partnerorderId;
        @XmlElement(required = true)
        protected String refundSeq;
        @XmlElement(required = true)
        protected String orderQuantity;
        @XmlElement(required = true)
        protected String refundResult;
        @XmlElement(required = true)
        protected String refundQuantity;
        @XmlElement(required = true)
        protected String orderRefundPrice;
        @XmlElement(required = true)
        protected String orderRefundCharge;

        /**
         * Gets the value of the partnerorderId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPartnerorderId() {
            return partnerorderId;
        }

        /**
         * Sets the value of the partnerorderId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPartnerorderId(String value) {
            this.partnerorderId = value;
        }

        /**
         * Gets the value of the refundSeq property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefundSeq() {
            return refundSeq;
        }

        /**
         * Sets the value of the refundSeq property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefundSeq(String value) {
            this.refundSeq = value;
        }

        /**
         * Gets the value of the orderQuantity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderQuantity() {
            return orderQuantity;
        }

        /**
         * Sets the value of the orderQuantity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderQuantity(String value) {
            this.orderQuantity = value;
        }

        /**
         * Gets the value of the refundResult property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefundResult() {
            return refundResult;
        }

        /**
         * Sets the value of the refundResult property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefundResult(String value) {
            this.refundResult = value;
        }

        /**
         * Gets the value of the refundQuantity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefundQuantity() {
            return refundQuantity;
        }

        /**
         * Sets the value of the refundQuantity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefundQuantity(String value) {
            this.refundQuantity = value;
        }

        /**
         * Gets the value of the orderRefundPrice property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderRefundPrice() {
            return orderRefundPrice;
        }

        /**
         * Sets the value of the orderRefundPrice property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderRefundPrice(String value) {
            this.orderRefundPrice = value;
        }

        /**
         * Gets the value of the orderRefundCharge property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderRefundCharge() {
            return orderRefundCharge;
        }

        /**
         * Sets the value of the orderRefundCharge property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderRefundCharge(String value) {
            this.orderRefundCharge = value;
        }

    }

}
