//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.25 at 03:35:22 ���� CST 
//


package com.lvmama.passport.processor.impl.client.jiuwang.model.v1.request;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ectrip.tour._2014.qmrequestdataschema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ectrip.tour._2014.qmrequestdataschema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ApplyOrderRefundByUserRequestBody }
     * 
     */
    public ApplyOrderRefundByUserRequestBody createApplyOrderRefundByUserRequestBody() {
        return new ApplyOrderRefundByUserRequestBody();
    }

    /**
     * Create an instance of {@link PushOrderRequestBody.OrderInfo.VisitPerson }
     * 
     */
    public PushOrderRequestBody.OrderInfo.VisitPerson createPushOrderRequestBodyOrderInfoVisitPerson() {
        return new PushOrderRequestBody.OrderInfo.VisitPerson();
    }

    /**
     * Create an instance of {@link CreateOrderRequestBody.OrderInfo }
     * 
     */
    public CreateOrderRequestBody.OrderInfo createCreateOrderRequestBodyOrderInfo() {
        return new CreateOrderRequestBody.OrderInfo();
    }

    /**
     * Create an instance of {@link CreateOrderRequestBody.OrderInfo.Product }
     * 
     */
    public CreateOrderRequestBody.OrderInfo.Product createCreateOrderRequestBodyOrderInfoProduct() {
        return new CreateOrderRequestBody.OrderInfo.Product();
    }

    /**
     * Create an instance of {@link NoticeOrderEticketSendedRequestBody }
     * 
     */
    public NoticeOrderEticketSendedRequestBody createNoticeOrderEticketSendedRequestBody() {
        return new NoticeOrderEticketSendedRequestBody();
    }

    /**
     * Create an instance of {@link CreateOrderRequestBody.OrderInfo.ContactPerson }
     * 
     */
    public CreateOrderRequestBody.OrderInfo.ContactPerson createCreateOrderRequestBodyOrderInfoContactPerson() {
        return new CreateOrderRequestBody.OrderInfo.ContactPerson();
    }

    /**
     * Create an instance of {@link NoticeOrderConsumedRequestBody.OrderInfo }
     * 
     */
    public NoticeOrderConsumedRequestBody.OrderInfo createNoticeOrderConsumedRequestBodyOrderInfo() {
        return new NoticeOrderConsumedRequestBody.OrderInfo();
    }

    /**
     * Create an instance of {@link RequestBody }
     * 
     */
    public RequestBody createRequestBody() {
        return new RequestBody();
    }

    /**
     * Create an instance of {@link ApplyOrderRefundByUserRequestBody.OrderInfo.VisitPerson }
     * 
     */
    public ApplyOrderRefundByUserRequestBody.OrderInfo.VisitPerson createApplyOrderRefundByUserRequestBodyOrderInfoVisitPerson() {
        return new ApplyOrderRefundByUserRequestBody.OrderInfo.VisitPerson();
    }

    /**
     * Create an instance of {@link ApplyOrderRefundByUserRequestBody.OrderInfo }
     * 
     */
    public ApplyOrderRefundByUserRequestBody.OrderInfo createApplyOrderRefundByUserRequestBodyOrderInfo() {
        return new ApplyOrderRefundByUserRequestBody.OrderInfo();
    }

    /**
     * Create an instance of {@link NoticeOrderRefundApproveResultRequestBody.OrderInfo }
     * 
     */
    public NoticeOrderRefundApproveResultRequestBody.OrderInfo createNoticeOrderRefundApproveResultRequestBodyOrderInfo() {
        return new NoticeOrderRefundApproveResultRequestBody.OrderInfo();
    }

    /**
     * Create an instance of {@link NoticeOrderRefundedByOTARequestBody.OrderInfo }
     * 
     */
    public NoticeOrderRefundedByOTARequestBody.OrderInfo createNoticeOrderRefundedByOTARequestBodyOrderInfo() {
        return new NoticeOrderRefundedByOTARequestBody.OrderInfo();
    }

    /**
     * Create an instance of {@link GetOrderByOTARequestBody }
     * 
     */
    public GetOrderByOTARequestBody createGetOrderByOTARequestBody() {
        return new GetOrderByOTARequestBody();
    }

    /**
     * Create an instance of {@link RequestHeader }
     * 
     */
    public RequestHeader createRequestHeader() {
        return new RequestHeader();
    }

    /**
     * Create an instance of {@link PushOrderRequestBody.OrderInfo }
     * 
     */
    public PushOrderRequestBody.OrderInfo createPushOrderRequestBodyOrderInfo() {
        return new PushOrderRequestBody.OrderInfo();
    }

    /**
     * Create an instance of {@link PushOrderRequestBody.OrderInfo.ContactPerson }
     * 
     */
    public PushOrderRequestBody.OrderInfo.ContactPerson createPushOrderRequestBodyOrderInfoContactPerson() {
        return new PushOrderRequestBody.OrderInfo.ContactPerson();
    }

    /**
     * Create an instance of {@link NoticeOrderConsumedRequestBody }
     * 
     */
    public NoticeOrderConsumedRequestBody createNoticeOrderConsumedRequestBody() {
        return new NoticeOrderConsumedRequestBody();
    }

    /**
     * Create an instance of {@link GetProductByOTARequestBody }
     * 
     */
    public GetProductByOTARequestBody createGetProductByOTARequestBody() {
        return new GetProductByOTARequestBody();
    }

    /**
     * Create an instance of {@link PayOrderRequestBody }
     * 
     */
    public PayOrderRequestBody createPayOrderRequestBody() {
        return new PayOrderRequestBody();
    }

    /**
     * Create an instance of {@link NoticeProductChangedRequestBody }
     * 
     */
    public NoticeProductChangedRequestBody createNoticeProductChangedRequestBody() {
        return new NoticeProductChangedRequestBody();
    }

    /**
     * Create an instance of {@link ApplyOrderRefundByUserRequestBody.OrderInfo.VisitPerson.Person }
     * 
     */
    public ApplyOrderRefundByUserRequestBody.OrderInfo.VisitPerson.Person createApplyOrderRefundByUserRequestBodyOrderInfoVisitPersonPerson() {
        return new ApplyOrderRefundByUserRequestBody.OrderInfo.VisitPerson.Person();
    }

    /**
     * Create an instance of {@link PushOrderRequestBody }
     * 
     */
    public PushOrderRequestBody createPushOrderRequestBody() {
        return new PushOrderRequestBody();
    }

    /**
     * Create an instance of {@link NoticeOrderEticketSendedRequestBody.OrderInfo }
     * 
     */
    public NoticeOrderEticketSendedRequestBody.OrderInfo createNoticeOrderEticketSendedRequestBodyOrderInfo() {
        return new NoticeOrderEticketSendedRequestBody.OrderInfo();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link SendOrderEticketRequestBody }
     * 
     */
    public SendOrderEticketRequestBody createSendOrderEticketRequestBody() {
        return new SendOrderEticketRequestBody();
    }

    /**
     * Create an instance of {@link PayOrderRequestBody.OrderInfo }
     * 
     */
    public PayOrderRequestBody.OrderInfo createPayOrderRequestBodyOrderInfo() {
        return new PayOrderRequestBody.OrderInfo();
    }

    /**
     * Create an instance of {@link CreateOrderRequestBody.OrderInfo.VisitPerson }
     * 
     */
    public CreateOrderRequestBody.OrderInfo.VisitPerson createCreateOrderRequestBodyOrderInfoVisitPerson() {
        return new CreateOrderRequestBody.OrderInfo.VisitPerson();
    }

    /**
     * Create an instance of {@link CreateOrderRequestBody }
     * 
     */
    public CreateOrderRequestBody createCreateOrderRequestBody() {
        return new CreateOrderRequestBody();
    }

    /**
     * Create an instance of {@link NoticeOrderRefundApproveResultRequestBody }
     * 
     */
    public NoticeOrderRefundApproveResultRequestBody createNoticeOrderRefundApproveResultRequestBody() {
        return new NoticeOrderRefundApproveResultRequestBody();
    }

    /**
     * Create an instance of {@link NoticeOrderRefundedByOTARequestBody }
     * 
     */
    public NoticeOrderRefundedByOTARequestBody createNoticeOrderRefundedByOTARequestBody() {
        return new NoticeOrderRefundedByOTARequestBody();
    }

    /**
     * Create an instance of {@link CreateOrderRequestBody.OrderInfo.VisitPerson.Person }
     * 
     */
    public CreateOrderRequestBody.OrderInfo.VisitPerson.Person createCreateOrderRequestBodyOrderInfoVisitPersonPerson() {
        return new CreateOrderRequestBody.OrderInfo.VisitPerson.Person();
    }

    /**
     * Create an instance of {@link PushOrderRequestBody.OrderInfo.VisitPerson.Person }
     * 
     */
    public PushOrderRequestBody.OrderInfo.VisitPerson.Person createPushOrderRequestBodyOrderInfoVisitPersonPerson() {
        return new PushOrderRequestBody.OrderInfo.VisitPerson.Person();
    }

    /**
     * Create an instance of {@link SendOrderEticketRequestBody.OrderInfo }
     * 
     */
    public SendOrderEticketRequestBody.OrderInfo createSendOrderEticketRequestBodyOrderInfo() {
        return new SendOrderEticketRequestBody.OrderInfo();
    }

}
