$(function(){

	var companys = new Array( "万豪（Mariott）",
				"洲际（InterContinental）",
				"雅高（Accor）",
				"希尔顿（Hilton）",
				"喜达屋（Starwood）",
				"温德姆（Wyndham）",
				"凯悦（Hyatt）",
				"最佳西方（Best Western）",
				"凯宾斯基（Kempinski）",
				"香格里拉（Shangri-la）",
				"卡尔森（Carlson）",
				"费尔蒙莱佛士（Fairmont Raffles）",
				"四季（Four Seasons）",
				"文华东方（Mandarin Oriental）",
				"半岛（Pennisula）",
				"瑰丽（Rosewood）",
				"千禧（Millennium）",
				"郎廷（Langham）",
				"约克（York）",
				"日航（Nikko）",
				"大仓（Okura）",
				"悦榕庄（Banyan Tree）",
				"安缦（Aman）",
				"泛太平洋（Pan Pacific）",
				"雅诗阁（Ascott）",
				"地中海俱乐部（Club Med）",
				"卓美亚（Jumeirah）",
				"锦江（Jinjiang）",
				"开元（Kaiyuan）",
				"金陵（Jinling）",
				"华侨城（OCT）",
				"首旅建国",
				"雷迪森",
				"天伦",
				"港中旅（Metropark）",
				"海逸（Harbour Plaza）",
				"富豪（Regal）",
				"凯莱（Gloria）",
				"粤海（Guangdong）",
				"康年（Conifer）",
				"碧桂园（Country Garden）",
				"恒大",
				"华天",
				"海航",
				"阳光（Soluxe）",
				"华润",
				"东方嘉柏（Jasper）",
				"万达（Wanda）",
				"绿地（Greenland）",
				"星河湾（Charteau）",
				"蓝海",
				"古井",
				"君澜（Narada）",
				"岭南",
				"南苑",
				"岷山",
				"书香",
				"衡山",
				"中南",
				"远洲（S&N）",
				"通程",
				"世纪金源（Empark）",
				"中州",
				"宝隆",
				"美豪（Mehood）",
				"格兰云天（Grand Skylight）",
				"中信",
				"中旅",
				"银座",
				"钮宾凯",
				"华住（Huazhu）",
				"如家（Homeinns）",
				"桔子",
				"七天（7 days）",
				"格林豪泰（Green Tree）",
				"维也纳（Vienna）",
				"富驿时尚（Fx）",
				"都市",
				"布丁（Buddin）",
				"99旅馆连锁（99inns）",
				"爱尊客",
				"尚客优（Thankyou99）",
				"飘",
				"云上四季",
				"易佰",
				"艳阳天",
				"浦江之星",
				"中安",
				"禧龙",
				"肯定");
	
	var brands = [["丽嘉（Ritz-Carlton)","JW万豪（JW Mariott）","万豪（Mariott）","万丽（Renaissance）","万怡（Courtyard）","万豪行政公寓"],
	             ["洲际（InterContinental）","皇冠假日（Crowne Plaza）","假日（Holiday Inn）","智选假日（Holiday Inn Express）","英迪格（Indigo）"],
	             ["索菲特（Sofitel）","铂尔曼（Pullman）","美爵（Grand Mercure）","美憬阁（M Gallery）","诺富特（Novotel）","美居（Mercure）","宜必思（Ibis）"],
	             ["希尔顿（Holton）","康莱德（Conrad）","华尔道夫（Waldorf）","希尔顿逸林（Double Tree）","斯堪的克（Scandic）"],
	             ["瑞吉（St.Regis）","豪华精选（Luxury Collection）","威斯汀（Westin）","喜来登（Sheraton）","福朋喜来登（Four Points）","艾美（Le Meridien）","W酒店（W Hotels）","雅乐轩（Aloft）"],
	             ["温德姆至尊豪廷（Wyndham Grand Plaza Royale）","戴斯（Days Inn）","华美达（Ramada）","豪生（Howard Johnson）","速8（Super 8）"],
	             ["柏悦（Park Hyatt)","君悦（Grand Hyatt）","凯悦（Hyatt Regency）","安达仕（Andaz）"],
	             ["最佳西方（Best Western）"],
	             ["凯宾斯基（Kempinski）"],
	             ["香格里拉（Shangri-la）","嘉里（Kerry）","商贸（Traders）"],
	             ["丽晶（Regent）","丽笙（Radisson）","丽亭（Park Plaza）"],
	             ["莱佛士（Raffles）","费尔蒙特（Fairmont）","瑞士（Swissotel）"],
	             ["四季（Four Seasons）"],
	             ["文华（Mandarin Oriental）"],
	             ["半岛（Pennisula）"],
	             ["瑰丽（Rosewood）","新世界（New World）","贝尔特（Belt）"],
	             ["豪华千禧（Grand Millennium）","千禧（Millennium）","国敦（Copthorne）"],
	             ["朗廷（Langham）","郎豪（Langham Palace）","逸东（Eaton）"],
	             ["Center Parcs","皇家约克（Royal York）","York"],
	             ["日航（Nikko）"],
	             ["大仓（Okura）"],
	             ["悦榕庄（Banyan Tree）","悦椿（Angsana）"],
	             ["安缦（Aman）"],
	             ["泛太平洋（Pan Pacific）","派乐雅（Park Royal）"],
	             ["雅诗阁（Ascott）","盛捷（Somerset）","馨乐庭（Citadine）"],
	             ["地中海俱乐部（Club Med）"],
	             ["卓美亚（Jumeirah）"],
	             ["J酒店（J Hotel）","锦江（Jinjiang）","商悦（Marvel）","时尚旅（Smart）","锦江之星（Jinjiang Inn）"],
	             ["开元名都（New Century Grand）","开元（New Century）","开元曼居","大禹开元"],
	             ["金陵","金一村"],
	             ["华侨城（OCT）","奥斯廷（O-city）","城市客栈（City Inn）"],
	             ["建国","欣燕都"],
	             ["雷迪森","维嘉","怡莱"],
	             ["瑞廷","瑞格","瑞怡"],
	             ["维景国际（Grand Metropark）","维景（Metropark）","旅居（Traveler Inn）","旅居快捷（Traveler Inn Express）"],
	             ["海逸（Harbour Plaza）"],
	             ["富豪（Regal）"],
	             ["凯莱（Gloria）"],
	             ["粤海国际","粤海","粤海之星"],
	             ["乌托邦（Evopia）","康年（Conifer）","康年华（Chronicles）","方廷（Frontier）"],
	             ["碧桂园"],
	             ["恒大"],
	             ["华天"],
	             ["唐拉雅秀","海航","海航商务","海航快捷","紫荆花"],
	             ["阳光"],
	             ["木棉花（Kapok）"],
	             ["嘉柏（Jasper）"],
	             ["嘉华（Realm）","文华（Vista）","瑞华（Reign）"],
	             ["铂瑞（Primus）","铂骊（Qube）"],
	             ["星河湾（Charteau）"],
	             ["蓝海国际","蓝海"],
	             ["古井","君莱","城市之家"],
	             ["君澜","君亭"],
	             ["岭南花园","岭南东方","岭南精英","岭南经典","岭南国际公寓","岭南佳园"],
	             ["南苑","南苑e家"],
	             ["岷山饭店","安逸158"],
	             ["书香连锁"],
	             ["衡山"],
	             ["中南"],
	             ["远洲"],
	             ["通程"],
	             ["世纪金源（Empark）"],
	             ["中州国际大饭店","中州国际饭店","中州商务酒店","中州国际度假酒店","中州快捷酒店"],
	             ["宝隆（Baolong）","宝隆居家（Baolong Inns）"],
	             ["美豪（Mehood）"],
	             ["格兰云天（Grand Skylight）"],
	             ["中信酒店"],
	             ["中旅酒店","山水时尚"],
	             ["银座","银座佳驿"],
	             ["钮宾凯"],
	             ["禧玥","汉庭","全季","海友","星程"],
	             ["和颐（Yitel）","如家（Home Inns）","莫泰（Motel 168）"],
	             ["桔子水晶","桔子"],
	             ["七天"],
	             ["格林豪泰（Green Tree）"],
	             ["维也纳"],
	             ["泊逸精品酒店","富驿时尚酒店","富驿商旅酒店"],
	             ["都市118"],
	             ["布丁"],
	             ["99旅馆"],
	             ["爱尊客"],
	             ["尚客优快捷"],
	             ["飘Home"],
	             ["云上四季"],
	             ["锐思特（Rest）","易佰连锁"],
	             ["艳阳天"],
	             ["浦江之星"],
	             ["中安之家"],
	             ["禧龙"],
	             ["肯定连锁"]
	       ];
	var hotelCompanyVal = $("#hotelCompany").attr("val");
	var hotelBrandVal = $("#hotelBrand").attr("val");
	var selected_inx;
	$.each(companys,function(i,n){
		if(hotelCompanyVal == n){
			selected_inx = i;
		}
		$("#hotelCompany").append("<option value=\""+n+"\">"+n+"</option>");
	});
	$("#hotelCompany").change(function(){
		$("#hotelBrand").html("<option value=\"\">--请选择--</option>");
		var s_inx = $("#hotelCompany").get(0).selectedIndex;
		if(s_inx > 0 ){
			$.each(brands[s_inx-1],function(i,n){
				var sel_str ="";
				if(hotelBrandVal == n){
					sel_str = "selected=\"selected\"";
					hotelBrandVal="";
				}
				$("#hotelBrand").append("<option value=\""+n+"\" "+sel_str+" >"+n+"</option>");
			});
		}
	});
	if(selected_inx!=null){
		$("#hotelCompany").get(0).selectedIndex = selected_inx+1;
		$("#hotelCompany").change();
	}
});
