package com.lvmama.comm.abroad.po;

import java.io.Serializable;
import java.util.Date;

public class AbroadhotelOrdOrder implements Serializable{
	private static final long serialVersionUID = -8197749919057411286L;

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.ID
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    private Long id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.ORDER_NO
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    private String orderNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.PAYMENT_STATUS
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    private String paymentStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.OUGHT_PAY
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    private Long oughtPay;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.ACTUAL_PAY
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    private Long actualPay;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.APPROVE_STATUS
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    private String approveStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.DEAL_DESC
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    private String dealDesc;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.CANCEL_REASON
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    private String cancelReason;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.CANCEL_OPERATOR
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    private String cancelOperator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.CANCEL_TIME
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    private Date cancelTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.USER_MEMO
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    private String userMemo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.USER_REPLY
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    private String userReply;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.WAIT_PAYMENT
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    private Date waitPayment;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.USER_ID
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    private String userId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.ORDER_STATUS
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    private String orderStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.CHANNEL
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    private String channel;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.LAST_CANCEL_TIME
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    private Date lastCancelTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.CREATE_TIME
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    private Date createTime;
    
    private Date paymentTime;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.ID
     *
     * @return the value of LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.ID
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.ID
     *
     * @param id the value for LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.ID
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.ORDER_NO
     *
     * @return the value of LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.ORDER_NO
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.ORDER_NO
     *
     * @param orderNo the value for LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.ORDER_NO
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.PAYMENT_STATUS
     *
     * @return the value of LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.PAYMENT_STATUS
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public String getPaymentStatus() {
        return paymentStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.PAYMENT_STATUS
     *
     * @param paymentStatus the value for LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.PAYMENT_STATUS
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public void setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.OUGHT_PAY
     *
     * @return the value of LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.OUGHT_PAY
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public Long getOughtPay() {
        return oughtPay;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.OUGHT_PAY
     *
     * @param oughtPay the value for LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.OUGHT_PAY
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public void setOughtPay(Long oughtPay) {
        this.oughtPay = oughtPay;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.ACTUAL_PAY
     *
     * @return the value of LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.ACTUAL_PAY
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public Long getActualPay() {
        return actualPay;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.ACTUAL_PAY
     *
     * @param actualPay the value for LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.ACTUAL_PAY
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public void setActualPay(Long actualPay) {
        this.actualPay = actualPay;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.APPROVE_STATUS
     *
     * @return the value of LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.APPROVE_STATUS
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public String getApproveStatus() {
        return approveStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.APPROVE_STATUS
     *
     * @param approveStatus the value for LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.APPROVE_STATUS
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public void setApproveStatus(String approveStatus) {
        this.approveStatus = approveStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.DEAL_DESC
     *
     * @return the value of LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.DEAL_DESC
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public String getDealDesc() {
        return dealDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.DEAL_DESC
     *
     * @param dealDesc the value for LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.DEAL_DESC
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public void setDealDesc(String dealDesc) {
        this.dealDesc = dealDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.CANCEL_REASON
     *
     * @return the value of LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.CANCEL_REASON
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public String getCancelReason() {
        return cancelReason;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.CANCEL_REASON
     *
     * @param cancelReason the value for LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.CANCEL_REASON
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public void setCancelReason(String cancelReason) {
        this.cancelReason = cancelReason;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.CANCEL_OPERATOR
     *
     * @return the value of LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.CANCEL_OPERATOR
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public String getCancelOperator() {
        return cancelOperator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.CANCEL_OPERATOR
     *
     * @param cancelOperator the value for LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.CANCEL_OPERATOR
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public void setCancelOperator(String cancelOperator) {
        this.cancelOperator = cancelOperator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.CANCEL_TIME
     *
     * @return the value of LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.CANCEL_TIME
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public Date getCancelTime() {
        return cancelTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.CANCEL_TIME
     *
     * @param cancelTime the value for LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.CANCEL_TIME
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public void setCancelTime(Date cancelTime) {
        this.cancelTime = cancelTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.USER_MEMO
     *
     * @return the value of LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.USER_MEMO
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public String getUserMemo() {
        return userMemo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.USER_MEMO
     *
     * @param userMemo the value for LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.USER_MEMO
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public void setUserMemo(String userMemo) {
        this.userMemo = userMemo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.USER_REPLY
     *
     * @return the value of LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.USER_REPLY
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public String getUserReply() {
        return userReply;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.USER_REPLY
     *
     * @param userReply the value for LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.USER_REPLY
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public void setUserReply(String userReply) {
        this.userReply = userReply;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.WAIT_PAYMENT
     *
     * @return the value of LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.WAIT_PAYMENT
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public Date getWaitPayment() {
        return waitPayment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.WAIT_PAYMENT
     *
     * @param waitPayment the value for LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.WAIT_PAYMENT
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public void setWaitPayment(Date waitPayment) {
        this.waitPayment = waitPayment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.USER_ID
     *
     * @return the value of LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.USER_ID
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.USER_ID
     *
     * @param userId the value for LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.USER_ID
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.ORDER_STATUS
     *
     * @return the value of LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.ORDER_STATUS
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.ORDER_STATUS
     *
     * @param orderStatus the value for LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.ORDER_STATUS
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.CHANNEL
     *
     * @return the value of LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.CHANNEL
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.CHANNEL
     *
     * @param channel the value for LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.CHANNEL
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public void setChannel(String channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.LAST_CANCEL_TIME
     *
     * @return the value of LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.LAST_CANCEL_TIME
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public Date getLastCancelTime() {
        return lastCancelTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.LAST_CANCEL_TIME
     *
     * @param lastCancelTime the value for LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.LAST_CANCEL_TIME
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public void setLastCancelTime(Date lastCancelTime) {
        this.lastCancelTime = lastCancelTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.CREATE_TIME
     *
     * @return the value of LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.CREATE_TIME
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.CREATE_TIME
     *
     * @param createTime the value for LVMAMA_SUPER.ABROADHOTEL_ORD_ORDER.CREATE_TIME
     *
     * @abatorgenerated Wed Apr 25 10:43:12 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

	public Date getPaymentTime() {
		return paymentTime;
	}

	public void setPaymentTime(Date paymentTime) {
		this.paymentTime = paymentTime;
	}
}