package com.lvmama.comm.pet.po.email;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class EmailContent implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -8386798440663539086L;

	private List<EmailAttachment> emailAttachments;
	
	private String contentText;
	
	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.EMAIL_CONTENT.CONTENT_ID
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    private Long contentId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.EMAIL_CONTENT.SUBJECT
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    private String subject;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.EMAIL_CONTENT.CONTENT_FILE_ID
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    private Long contentFileId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.EMAIL_CONTENT.MAIL_HEADER
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    private String mailHeader;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.EMAIL_CONTENT.FROM_ADDRESS
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    private String fromAddress;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.EMAIL_CONTENT.FROM_NAME
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    private String fromName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.EMAIL_CONTENT.TO
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    private String toAddress;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.EMAIL_CONTENT.STATUS
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    private String status;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.EMAIL_CONTENT.CREATE_TIME
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    private Date createTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.EMAIL_CONTENT.SEND_TIME
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    private Date sendTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.EMAIL_CONTENT.SEND_COUNT
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    private Integer sendCount;
    private String ccAddress;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.EMAIL_CONTENT.CONTENT_ID
     *
     * @return the value of LVMAMA_SUPER.EMAIL_CONTENT.CONTENT_ID
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    public Long getContentId() {
        return contentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.EMAIL_CONTENT.CONTENT_ID
     *
     * @param contentId the value for LVMAMA_SUPER.EMAIL_CONTENT.CONTENT_ID
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    public void setContentId(Long contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.EMAIL_CONTENT.SUBJECT
     *
     * @return the value of LVMAMA_SUPER.EMAIL_CONTENT.SUBJECT
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.EMAIL_CONTENT.SUBJECT
     *
     * @param subject the value for LVMAMA_SUPER.EMAIL_CONTENT.SUBJECT
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.EMAIL_CONTENT.CONTENT_FILE_ID
     *
     * @return the value of LVMAMA_SUPER.EMAIL_CONTENT.CONTENT_FILE_ID
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    public Long getContentFileId() {
        return contentFileId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.EMAIL_CONTENT.CONTENT_FILE_ID
     *
     * @param contentFileId the value for LVMAMA_SUPER.EMAIL_CONTENT.CONTENT_FILE_ID
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    public void setContentFileId(Long contentFileId) {
        this.contentFileId = contentFileId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.EMAIL_CONTENT.MAIL_HEADER
     *
     * @return the value of LVMAMA_SUPER.EMAIL_CONTENT.MAIL_HEADER
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    public String getMailHeader() {
        return mailHeader;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.EMAIL_CONTENT.MAIL_HEADER
     *
     * @param mailHeader the value for LVMAMA_SUPER.EMAIL_CONTENT.MAIL_HEADER
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    public void setMailHeader(String mailHeader) {
        this.mailHeader = mailHeader;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.EMAIL_CONTENT.FROM_ADDRESS
     *
     * @return the value of LVMAMA_SUPER.EMAIL_CONTENT.FROM_ADDRESS
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    public String getFromAddress() {
        return fromAddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.EMAIL_CONTENT.FROM_ADDRESS
     *
     * @param fromAddress the value for LVMAMA_SUPER.EMAIL_CONTENT.FROM_ADDRESS
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    public void setFromAddress(String fromAddress) {
        this.fromAddress = fromAddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.EMAIL_CONTENT.FROM_NAME
     *
     * @return the value of LVMAMA_SUPER.EMAIL_CONTENT.FROM_NAME
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    public String getFromName() {
        return fromName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.EMAIL_CONTENT.FROM_NAME
     *
     * @param fromName the value for LVMAMA_SUPER.EMAIL_CONTENT.FROM_NAME
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    public void setFromName(String fromName) {
        this.fromName = fromName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.EMAIL_CONTENT.TO
     *
     * @return the value of LVMAMA_SUPER.EMAIL_CONTENT.TO
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    public String getToAddress() {
        return toAddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.EMAIL_CONTENT.TO
     *
     * @param to the value for LVMAMA_SUPER.EMAIL_CONTENT.TO
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    public void setToAddress(String toAddress) {
        this.toAddress = toAddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.EMAIL_CONTENT.STATUS
     *
     * @return the value of LVMAMA_SUPER.EMAIL_CONTENT.STATUS
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.EMAIL_CONTENT.STATUS
     *
     * @param status the value for LVMAMA_SUPER.EMAIL_CONTENT.STATUS
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.EMAIL_CONTENT.CREATE_TIME
     *
     * @return the value of LVMAMA_SUPER.EMAIL_CONTENT.CREATE_TIME
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.EMAIL_CONTENT.CREATE_TIME
     *
     * @param createTime the value for LVMAMA_SUPER.EMAIL_CONTENT.CREATE_TIME
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.EMAIL_CONTENT.SEND_TIME
     *
     * @return the value of LVMAMA_SUPER.EMAIL_CONTENT.SEND_TIME
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.EMAIL_CONTENT.SEND_TIME
     *
     * @param sendTime the value for LVMAMA_SUPER.EMAIL_CONTENT.SEND_TIME
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.EMAIL_CONTENT.SEND_COUNT
     *
     * @return the value of LVMAMA_SUPER.EMAIL_CONTENT.SEND_COUNT
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    public Integer getSendCount() {
        return sendCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.EMAIL_CONTENT.SEND_COUNT
     *
     * @param sendCount the value for LVMAMA_SUPER.EMAIL_CONTENT.SEND_COUNT
     *
     * @abatorgenerated Thu Aug 02 16:45:15 CST 2012
     */
    public void setSendCount(Integer sendCount) {
        this.sendCount = sendCount;
    }
	public List<EmailAttachment> getEmailAttachments() {
		return emailAttachments;
	}

	public void setEmailAttachments(List<EmailAttachment> emailAttachments) {
		this.emailAttachments = emailAttachments;
	}

	public String getContentText() {
		return contentText;
	}

	public void setContentText(String contentText) {
		this.contentText = contentText;
	}

	public String getCcAddress() {
		return ccAddress;
	}

	public void setCcAddress(String ccAddress) {
		this.ccAddress = ccAddress;
	}
}