package com.lvmama.comm.pet.po.email;

import java.io.Serializable;

public class EmailAttachment implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -5437430556550063911L;

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.EMAIL_ATTACHMENT.EMAIL_ATTACHMENT_ID
     *
     * @abatorgenerated Thu Aug 02 16:45:29 CST 2012
     */
    private Long emailAttachmentId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.EMAIL_ATTACHMENT.MAIL_CONTENT_ID
     *
     * @abatorgenerated Thu Aug 02 16:45:29 CST 2012
     */
    private Long mailContentId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.EMAIL_ATTACHMENT.FILE_NAME
     *
     * @abatorgenerated Thu Aug 02 16:45:29 CST 2012
     */
    private String fileName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column LVMAMA_SUPER.EMAIL_ATTACHMENT.FILE_ID
     *
     * @abatorgenerated Thu Aug 02 16:45:29 CST 2012
     */
    private Long fileId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.EMAIL_ATTACHMENT.EMAIL_ATTACHMENT_ID
     *
     * @return the value of LVMAMA_SUPER.EMAIL_ATTACHMENT.EMAIL_ATTACHMENT_ID
     *
     * @abatorgenerated Thu Aug 02 16:45:29 CST 2012
     */
    public Long getEmailAttachmentId() {
        return emailAttachmentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.EMAIL_ATTACHMENT.EMAIL_ATTACHMENT_ID
     *
     * @param emailAttachmentId the value for LVMAMA_SUPER.EMAIL_ATTACHMENT.EMAIL_ATTACHMENT_ID
     *
     * @abatorgenerated Thu Aug 02 16:45:29 CST 2012
     */
    public void setEmailAttachmentId(Long emailAttachmentId) {
        this.emailAttachmentId = emailAttachmentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.EMAIL_ATTACHMENT.MAIL_CONTENT_ID
     *
     * @return the value of LVMAMA_SUPER.EMAIL_ATTACHMENT.MAIL_CONTENT_ID
     *
     * @abatorgenerated Thu Aug 02 16:45:29 CST 2012
     */
    public Long getMailContentId() {
        return mailContentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.EMAIL_ATTACHMENT.MAIL_CONTENT_ID
     *
     * @param mailContentId the value for LVMAMA_SUPER.EMAIL_ATTACHMENT.MAIL_CONTENT_ID
     *
     * @abatorgenerated Thu Aug 02 16:45:29 CST 2012
     */
    public void setMailContentId(Long mailContentId) {
        this.mailContentId = mailContentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.EMAIL_ATTACHMENT.FILE_NAME
     *
     * @return the value of LVMAMA_SUPER.EMAIL_ATTACHMENT.FILE_NAME
     *
     * @abatorgenerated Thu Aug 02 16:45:29 CST 2012
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.EMAIL_ATTACHMENT.FILE_NAME
     *
     * @param fileName the value for LVMAMA_SUPER.EMAIL_ATTACHMENT.FILE_NAME
     *
     * @abatorgenerated Thu Aug 02 16:45:29 CST 2012
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column LVMAMA_SUPER.EMAIL_ATTACHMENT.FILE_ID
     *
     * @return the value of LVMAMA_SUPER.EMAIL_ATTACHMENT.FILE_ID
     *
     * @abatorgenerated Thu Aug 02 16:45:29 CST 2012
     */
    public Long getFileId() {
        return fileId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column LVMAMA_SUPER.EMAIL_ATTACHMENT.FILE_ID
     *
     * @param fileId the value for LVMAMA_SUPER.EMAIL_ATTACHMENT.FILE_ID
     *
     * @abatorgenerated Thu Aug 02 16:45:29 CST 2012
     */
    public void setFileId(Long fileId) {
        this.fileId = fileId;
    }
}