//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.21 at 05:21:00 PM CST 
//


package com.lvmama.elong.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement; 
import java.util.List; 
import com.alibaba.fastjson.annotation.JSONField;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreditCardWithStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreditCardWithStatus">
 *   &lt;complexContent>
 *     &lt;extension base="{}CreditCard">
 *       &lt;sequence>
 *         &lt;element name="ProcessType" type="{}EnumCreditCardProcessType"/>
 *         &lt;element name="Status" type="{}EnumCreditCardStatus"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditCardWithStatus", propOrder = {
    "processType",
    "status"
})
public class CreditCardWithStatus
    extends CreditCard
{

    @JSONField(name = "ProcessType")
    protected EnumCreditCardProcessType processType;
    @JSONField(name = "Status")
    protected EnumCreditCardStatus status;

    /**
     * Gets the value of the processType property.
     * 
     * @return
     *     possible object is
     *     {@link EnumCreditCardProcessType }
     *     
     */
    public EnumCreditCardProcessType getProcessType() {
        return processType;
    }

    /**
     * Sets the value of the processType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumCreditCardProcessType }
     *     
     */
    public void setProcessType(EnumCreditCardProcessType value) {
        this.processType = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link EnumCreditCardStatus }
     *     
     */
    public EnumCreditCardStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumCreditCardStatus }
     *     
     */
    public void setStatus(EnumCreditCardStatus value) {
        this.status = value;
    }

}
