//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.21 at 05:21:00 PM CST 
//


package com.lvmama.elong.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnumVirtualCardBusinessType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EnumVirtualCardBusinessType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Gurantee"/>
 *     &lt;enumeration value="GlobalHotel"/>
 *     &lt;enumeration value="Prepay"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EnumVirtualCardBusinessType")
@XmlEnum
public enum EnumVirtualCardBusinessType {

    @XmlEnumValue("Gurantee")
    Gurantee("Gurantee"),
    @XmlEnumValue("GlobalHotel")
    GlobalHotel("GlobalHotel"),
    @XmlEnumValue("Prepay")
    Prepay("Prepay");
    private final String value;

    EnumVirtualCardBusinessType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EnumVirtualCardBusinessType fromValue(String v) {
        for (EnumVirtualCardBusinessType c: EnumVirtualCardBusinessType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
