package com.lvmama.passport.processor.impl.client.time100;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * 度假API
 *
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-06T10:49:28.250+08:00
 * Generated source version: 2.7.5
 * 
 */
@WebServiceClient(name = "Holiday", 
                  wsdlLocation = "Holiday.wsdl",
                  targetNamespace = "http://www.time100.net/") 
public class Holiday extends MyService {
    public final static QName SERVICE = new QName("http://www.time100.net/", "Holiday");
    public final static QName HolidaySoap = new QName("http://www.time100.net/", "HolidaySoap");
    public final static QName HolidaySoap12 = new QName("http://www.time100.net/", "HolidaySoap12");
    public Holiday(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Holiday(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns HolidaySoap
     */
    @WebEndpoint(name = "HolidaySoap")
    public HolidaySoap getHolidaySoap() {
        return super.getPort(HolidaySoap, HolidaySoap.class);
    }

    /**
     *
     * @return
     *     returns HolidaySoap
     */
    @WebEndpoint(name = "HolidaySoap12")
    public HolidaySoap getHolidaySoap12() {
        return super.getPort(HolidaySoap12, HolidaySoap.class);
    }

}
