<!--index_footer-->
<link href="http://pic.lvmama.com/styles/oldlvmama/style/pc_index/footer.css" rel="stylesheet" type="text/css" />
<div class="index_footer" style="margin:0 auto;"><a href="http://www.lvmama.com/public/about_lvmama">关于我们</a> <a href="http://www.lvmama.com/public/site_map">网站地图</a> <a href="http://www.lvmama.com/public/help">帮助中心</a> <a href="http://www.lvmama.com/public/links">友情链接</a> <a href="http://www.lvmama.com/public/jobs">诚聘英才</a> <a href="http://www.lvmama.com/userCenter/user/transItfeedBack.do">意见反馈</a><br />

Copyright © 2010 www.lvmama.com. 景域旅游运营集团版权所有　沪ICP备07509677　增值电信业务经营许可证编号：<span><a target="_blank" href="http://pic.lvmama.com/img/ICP.jpg">沪B2-20100030</a></span>
<p class="fttencent"><span>驴妈妈驴友交流群：<strong>123472048</strong></span>  <span>意见/建议QQ群：<strong>76888566</strong></span></p>
<p class="index_footer_img"><a href="http://www.miibeian.gov.cn/" target="_blank"><img src="http://pic.lvmama.com/img/index_foot_pic1.gif" /></a><a href="http://www.cyberpolice.cn" target="_blank"><img src="http://pic.lvmama.com/img/index_foot_pic3.gif" /></a><a href="https://www.alipay.com/aip/aip_validate_list.htm?trust_id=AIP0102495" target="_blank"><img src="http://pic.lvmama.com/img/alipay.gif" /></a><a target="_blank" href="http://www.itrust.org.cn/yz/pjwx.asp?wm=1664396140"><img src="http://pic.lvmama.com/img/itrust.jpg"></a></p>
</div>
<div class="fl">
<p>当季旅游：<a href="http://happyvalley.lvmama.com/" target="_blank">上海欢乐谷</a> <a href="http://info.lvmama.com/" target="_blank">旅游资讯</a> <a href="http://www.lvmama.com/dest/shanghaiyeshengdongwuyuan" target="_blank">上海野生动物园</a> <a href="http://www.lvmama.com/zt/orientalpearl" target="_blank">上海东方明珠</a> <a href="http://www.lvmama.com/dest/changzhoukonglongyuan" target="_blank">常州恐龙园</a> <a href="http://www.lvmama.com/dest/changlongshuishangleyuan" target="_blank">长隆水上乐园</a> <a href="http://www.lvmama.com/dest/suzhouleyuan" target="_blank">苏州乐园</a> <a href="http://www.lvmama.com/dest/hengdian" target="_blank">横店影视城</a> <a href="http://www.lvmama.com/dest/dongbuhuaqiaocheng" target="_blank">东部华侨城</a> <a href="http://www.lvmama.com/dest/xiangjiangyeshengdongwuyuan" target="_blank">香江野生动物园</a> <a href="http://www.lvmama.com/dest/dalianfaxianwangguo" target="_blank">发现王国</a> <a href="http://www.lvmama.com/dest/xixishidi" target="_blank">西溪湿地</a> <a href="http://www.lvmama.com/dest/shenzhenhuanlegu" target="_blank">深圳欢乐谷</a></p>
<p> <a href="http://www.lvmama.com/dest/zhexidaxiagu" target="_blank">浙西大峡谷</a> <a href="http://www.lvmama.com/dest/baguacun" target="_blank">诸葛八卦村</a> <a href="http://www.lvmama.com/dest/jidihaiyangshijie" target="_blank">青岛海洋世界</a> <a href="http://www.lvmama.com/dest/shanghaishiboyuan" target="_blank">上海世博会</a> <a href="http://www.lvmama.com/dest/dushafurenlaxiangguan" target="_blank">杜莎夫人蜡像馆</a> <a href="http://www.lvmama.com/dest/xitang" target="_blank">西塘</a> <a href="http://www.lvmama.com/dest/tongxiang" target="_blank">乌镇</a> <a href="http://www.lvmama.com/dest/zhouzhuangguzhen" target="_blank">周庄</a> <a href="http://www.lvmama.com/dest/changlongdamaxi" target="_blank">长隆大马戏</a> <a href="http://www.lvmama.com/dest/shajiabang" target="_blank">沙家浜</a> <a href="http://www.lvmama.com/dest/qiandaohusenlinyangba" target="_blank">千岛湖</a> <a href="http://www.lvmama.com/dest/shuangxizhuhai" target="_blank">双溪漂流</a> <a href="http://www.lvmama.com/dest/yinxiangxihu" target="_blank">印象西湖</a> <a href="http://www.lvmama.com/dest/qiangshenghuangpu" target="_blank">浦江游览</a> <a href="http://www.lvmama.com/dest/jinmaodasha" target="_blank">金茂大厦</a> <a href="http://www.lvmama.com/dest/dongpinggongyuan" target="_blank">崇明岛</a></p> 
	<p>旅游推荐：    <a href="http://info.lvmama.com/" target="_blank">驴妈妈资讯</a> <a href="http://www.lvmama.com/lp/shanghaishibohui/" target="_blank">上海世博会</a>  <a href="http://happyvalley.lvmama.com/" target="_blank">上海欢乐谷</a> <a href="http://happyvalley.lvmama.com/" target="_blank">成都欢乐谷</a> <a href="http://happyvalley.lvmama.com/" target="_blank">深圳欢乐谷</a> <a href="http://www.lvmama.com/lp/zhouzhuanglvyou/" target="_blank">周庄旅游</a>  <a href="http://www.lvmama.com/lp/wuzhenlvyou/" target="_blank">乌镇旅游</a>  <a href="http://www.lvmama.com/lp/xitanglvyou/" target="_blank">西塘旅游</a>  <a href="http://www.lvmama.com/lp/hongcunlvyou/" target="_blank">宏村旅游</a>  <a href="http://www.lvmama.com/lp/tonglilvyou/" target="_blank">同里旅游</a>  <a href="http://www.lvmama.com/lp/disinileyuan/" target="_blank">香港迪斯尼乐园</a>  <a href="http://www.lvmama.com/lp/xidilvyou/" target="_blank">西递旅游 </a>  <a href="http://www.lvmama.com/lp/xjzoo/" target="_blank">香江野生动物园</a>  <a href="http://www.lvmama.com/lp/konglongyuan/" target="_blank">常州恐龙园</a> <a href="http://www.lvmama.com/site/guilin.do" target="_blank">桂林旅游</a></p>
<p>城市目的地索引：<a href="http://sitemap.lvmama.com/sitemap-223.html">1</a>  <a href="http://sitemap.lvmama.com/sitemap-224.html">2</a>  <a href="http://sitemap.lvmama.com/sitemap-225.html">3</a>  <a href="http://sitemap.lvmama.com/sitemap-226.html">4</a>  <a href="http://sitemap.lvmama.com/sitemap-227.html">5</a>  <a href="http://sitemap.lvmama.com/sitemap-228.html">6</a>  <a href="http://sitemap.lvmama.com/sitemap-229.html">7</a>  <a href="http://sitemap.lvmama.com/sitemap-230.html">8</a>  <a href="http://sitemap.lvmama.com/sitemap-231.html">9</a>  <a href="http://sitemap.lvmama.com/sitemap-232.html">10</a>  <a href="http://sitemap.lvmama.com/sitemap-233.html">11</a>  <a href="http://sitemap.lvmama.com/sitemap-234.html">12</a>  <a href="http://sitemap.lvmama.com/sitemap-235.html">13</a>  <a href="http://sitemap.lvmama.com/sitemap-236.html">14</a>  </p>
</div>
<#include "/common/mvHost.ftl"/>
