<!--index_footer-->
<link href="http://pic.lvmama.com/styles/pc_index/footer.css" rel="stylesheet" type="text/css" />
<div class="index_footer" style="margin:0 auto;"><a href="http://www.lvmama.com/public/about_lvmama">关于我们</a> <a href="http://www.lvmama.com/public/site_map">网站地图</a> <a href="http://www.lvmama.com/public/help">帮助中心</a> <a href="http://www.lvmama.com/public/links">友情链接</a> <a href="http://www.lvmama.com/public/jobs">诚聘英才</a> <a href="http://www.lvmama.com/userCenter/user/transItfeedBack.do">意见反馈</a><br />

Copyright © 2010 www.lvmama.com. 景域旅游运营集团版权所有　沪ICP备07509677　增值电信业务经营许可证编号：<span><a target="_blank" href="http://pic.lvmama.com/img/ICP.jpg">沪B2-20100030</a></span>
<p class="fttencent"><span>驴妈妈驴友交流群：<strong>123472048</strong></span>  <span>意见/建议QQ群：<strong>76888566</strong></span></p>
<p class="index_footer_img"><a href="http://www.miibeian.gov.cn/" target="_blank"><img src="http://pic.lvmama.com/img/index_foot_pic1.gif" /></a><a href="http://www.cyberpolice.cn" target="_blank"><img src="http://pic.lvmama.com/img/index_foot_pic3.gif" /></a><a href="https://www.alipay.com/aip/aip_validate_list.htm?trust_id=AIP0102495" target="_blank"><img src="http://pic.lvmama.com/img/alipay.gif" /></a><a target="_blank" href="http://www.itrust.org.cn/yz/pjwx.asp?wm=1664396140"><img src="http://pic.lvmama.com/img/itrust.jpg"></a></p>

</div>
<div class="fl">
	<p>合作网站：<a href="http://www.joyuchina.com/" target="_blank">景域</a> <a href="http://www.ctrip.com/" target="_blank">携程旅行网</a> <a href="http://www.2020china.com/" target="_blank">奇创</a></p>
	<p>友情链接： <a href="http://www.ynzql.com" target="_blank">云南旅游</a> <a href="http://travel.syd.com.cn" target="_blank">酒店宾馆</a> <a href="http://china.zyw.com/" target="_blank">电子商务资源网</a> <a href="http://www.wuyiguide.com/" target="_blank">武夷山自助游</a> <a href="http://www.ijia360.com/" target="_blank">全国自驾游</a> <a href="http://www.minxinhe.com/" target="_blank">石家庄</a> <a href="http://www.zhigou.com/" target="_blank">网上购物</a> <a href="http://www.yeedou.com/" target="_blank">购物搜索</a> <a href="http://www.6guilin.com/" target="_blank">桂林旅游</a> <a href="http://www.800zazhi.com/" target="_blank">800杂志</a> <a href="http://www.weamax.com/" target="_blank">互联网观察中心</a> <a href="http://www.pengzhilv.cn/" target="_blank">香港旅游</a> <a href="http://www.coroo.net/" target="_blank">可乐网</a> <a href="http://www.elicn.com/" target="_blank">易联国际机票网</a></p>
    <p> <a href="http://www.yourke.cn/" target="_blank">杭州旅游</a> <a href="http://www.zglyzl.com/" target="_blank">中国旅游纵览</a> <a href="http://www.gotobus.cn/" target="_blank">巴士旅游</a> <a href="http://www.wxwu.com/" target="_blank">物秀网</a> <a href="http://www.1hai.cn/" target="_blank">一嗨租车</a> <a href="http://network.pcpop.com/" target="_blank">泡泡网</a> <a href="http://hotel.kuxun.cn/" target="_blank">特价酒店预订</a> <a href="http://www.lvmama.com/place/120044/" target="_blank">上海欢乐谷门票</a>  <a href="http://www.lvmama.com/place/102926/" target="_blank">成都国色天香</a>  <a href="http://www.jiudian77.cn" target="_blank">7天连锁酒店</a>  <a href="http://www.cntsyy.com/" target="_blank">特价机票</a>  <a href="http://www.17you8.com/" target="_blank">一起游吧旅行网</a>  <a href="http://www.58guanjia.com/" target="_blank">旅游管家网</a> <a href="http://www.cnair.com/" target="_blank">中国航空旅游</a></p>
    <p> <a href="http://www.mipang.com/zhuanti/putuoshan/" target="_blank">普陀山旅游</a>  <a href="http://www.wulingshan.com.cn/" target="_blank">雾灵山</a>  <a href="http://www.tripmart.net.cn" target="_blank">畅游旅行网</a> <a href="http://www.8816.net/" target="_blank">北戴河旅游</a> <a href="http://www.jiayou360.com/" target="_blank">佳游网</a> <a href="http://www.uzai.com/" target="_blank">悠哉旅游</a> <a href="http://travel.poco.cn/" target="_blank">POCO旅游</a> <a href="http://travel.21cn.com/" target="_blank">21cn旅游</a> <a href="http://www.960rv.com/" target="_blank">960网</a> <a href="http://www.ccyts.com" target="_blank">成都旅行社</a> <a href="http://www.sccyts.com" target="_blank">九寨沟旅游</a> <a href="http://www.soworld.net
" target="_blank">搜世界旅游网</a> <a href="http://www.ccyts.com" target="_blank">成都旅行社</a> <a href="http://www.sccyts.com" target="_blank">九寨沟旅游</a>  <a href="http://www.meeting126.com/" target="_blank">长白山会议</a>  <a href="http://www.lvmama.com/public/links" target="_blank">>>更多</a></p>
    <p>旅游推荐：    <a href="http://www.lvmama.com/zt/orientalpearl/" target="_blank">东方明珠</a> <a href="http://info.lvmama.com/" target="_blank">驴妈妈资讯</a> <a href="http://www.lvmama.com/zt/hangzhou/" target="_blank">杭州旅游</a>  <a href="http://www.lvmama.com/zt/tonglu/" target="_blank">桐庐旅游</a>  <a href="http://www.lvmama.com/zt/linan/" target="_blank">临安旅游</a>  <a href="http://www.lvmama.com/zt/yangzhou/" target="_blank">扬州旅游</a>  <a href="http://www.lvmama.com/zt/sanya" target="_blank">三亚旅游</a>  <a href="http://www.lvmama.com/zt/shaoxing" target="_blank">绍兴旅游</a>  <a href="http://www.lvmama.com/zt/huangshan" target="_blank">黄山旅游 </a>  <a href="http://www.lvmama.com/zt/wuyuan/" target="_blank">婺源旅游</a>  <a href="http://www.lvmama.com/zt/ancient_towns" target="_blank">水乡古镇</a> <a href="http://wenquan.lvmama.com" target="_blank">温泉旅游</a>  <a href="http://www.lvmama.com/zt/fujian/" target="_blank">雁荡山</a>  <a href="http://www.lvmama.com/place/101171" target="_blank">西塘旅游</a>  <a href="http://www.lvmama.com/place/121200" target="_blank">成都欢乐谷</a>  <a href="http://www.lvmama.com/public/dest_summary/" target="_blank">目的地旅游</a></p>
<p>城市目的地索引：<a href="http://sitemap.lvmama.com/sitemap-31.html">1</a>  <a href="http://sitemap.lvmama.com/sitemap-32.html">2</a>   <a href="http://sitemap.lvmama.com/sitemap-33.html">3</a>   <a href="http://sitemap.lvmama.com/sitemap-34.html">4</a>   <a href="http://sitemap.lvmama.com/sitemap-35.html">5</a>   <a href="http://sitemap.lvmama.com/sitemap-36.html">6</a>   <a href="http://sitemap.lvmama.com/sitemap-37.html">7</a>   <a href="http://sitemap.lvmama.com/sitemap-38.html">8</a>   <a href="http://sitemap.lvmama.com/sitemap-39.html">9</a>   <a href="http://sitemap.lvmama.com/sitemap-40.html">10</a>   <a href="http://sitemap.lvmama.com/sitemap-41.html">11</a>   <a href="http://sitemap.lvmama.com/sitemap-42.html">12</a>   <a href="http://sitemap.lvmama.com/sitemap-43.html">13</a>   <a href="http://sitemap.lvmama.com/sitemap-44.html">14</a>   <a href="http://sitemap.lvmama.com/sitemap-45.html">15</a>   <a href="http://sitemap.lvmama.com/sitemap-46.html">16</a>   <a href="http://sitemap.lvmama.com/sitemap-47.html">17</a>   <a href="http://sitemap.lvmama.com/sitemap-48.html">18</a>   <a href="http://sitemap.lvmama.com/sitemap-49.html">19</a>   <a href="http://sitemap.lvmama.com/sitemap-50.html">20</a>   <a href="http://sitemap.lvmama.com/sitemap-51.html">21</a>   <a href="http://sitemap.lvmama.com/sitemap-52.html">22</a>   <a href="http://sitemap.lvmama.com/sitemap-53.html">23</a>   <a href="http://sitemap.lvmama.com/sitemap-54.html">24</a>   <a href="http://sitemap.lvmama.com/sitemap-55.html">25</a>   <a href="http://sitemap.lvmama.com/sitemap-56.html">26</a>   <a href="http://sitemap.lvmama.com/sitemap-57.html">27</a>   <a href="http://sitemap.lvmama.com/sitemap-58.html">28</a>   <a href="http://sitemap.lvmama.com/sitemap-59.html">29</a>   <a href="http://sitemap.lvmama.com/sitemap-60.html">30</a>   <a href="http://sitemap.lvmama.com/sitemap-61.html">31</a>   <a href="http://sitemap.lvmama.com/sitemap-62.html">32</a>   <a href="http://sitemap.lvmama.com/sitemap-63.html">33</a>   <a href="http://sitemap.lvmama.com/sitemap-64.html">34</a>   <a href="http://sitemap.lvmama.com/sitemap-65.html">35</a>   <a href="http://sitemap.lvmama.com/sitemap-66.html">36</a>   <a href="http://sitemap.lvmama.com/sitemap-67.html">37</a>   <a href="http://sitemap.lvmama.com/sitemap-68.html">38</a>   <a href="http://sitemap.lvmama.com/sitemap-69.html">39</a>   <a href="http://sitemap.lvmama.com/sitemap-70.html">40</a>   <a href="http://sitemap.lvmama.com/sitemap-71.html">41</a>   <a href="http://sitemap.lvmama.com/sitemap-72.html">42</a>   <a href="http://sitemap.lvmama.com/sitemap-73.html">43</a>   <a href="http://sitemap.lvmama.com/sitemap-74.html">44</a>   <a href="http://sitemap.lvmama.com/sitemap-75.html">45</a>   <a href="http://sitemap.lvmama.com/sitemap-76.html">46</a>   <a href="http://sitemap.lvmama.com/sitemap-77.html">47</a>   <a href="http://sitemap.lvmama.com/sitemap-78.html">48</a>   </p>
</div>
<#include "/WEB-INF/ftl/common/mvHost.ftl"/>