package com.lvmama.pet.email.dao;

import java.util.List;

import com.lvmama.comm.BaseIbatisDAO;
import com.lvmama.comm.pet.po.email.EmailAttachment;
public class EmailAttachmentDAO extends BaseIbatisDAO{

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table LVMAMA_SUPER.EMAIL_ATTACHMENT
     *
     * @abatorgenerated Thu Aug 02 16:45:29 CST 2012
     */
    public void insert(EmailAttachment record){
        super.insert("EMAIL_ATTACHMENT.insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table LVMAMA_SUPER.EMAIL_ATTACHMENT
     *
     * @abatorgenerated Thu Aug 02 16:45:29 CST 2012
     */
    public int updateByPrimaryKey(EmailAttachment record){
        int rows = super.update("EMAIL_ATTACHMENT.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table LVMAMA_SUPER.EMAIL_ATTACHMENT
     *
     * @abatorgenerated Thu Aug 02 16:45:29 CST 2012
     */
    public int updateByPrimaryKeySelective(EmailAttachment record){
        int rows = super.update("EMAIL_ATTACHMENT.updateByPrimaryKeySelective", record);
        return rows;
    }


    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table LVMAMA_SUPER.EMAIL_ATTACHMENT
     *
     * @abatorgenerated Thu Aug 02 16:45:29 CST 2012
     */
    public EmailAttachment selectByPrimaryKey(Long emailAttachmentId){
        EmailAttachment key = new EmailAttachment();
        key.setEmailAttachmentId(emailAttachmentId);
        EmailAttachment record = (EmailAttachment) super.queryForObject("EMAIL_ATTACHMENT.selectByPrimaryKey", key);
        return record;
    }


    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table LVMAMA_SUPER.EMAIL_ATTACHMENT
     *
     * @abatorgenerated Thu Aug 02 16:45:29 CST 2012
     */
    public int deleteByPrimaryKey(Long emailAttachmentId){
        EmailAttachment key = new EmailAttachment();
        key.setEmailAttachmentId(emailAttachmentId);
        int rows = super.delete("EMAIL_ATTACHMENT.deleteByPrimaryKey", key);
        return rows;
    }

    public List<EmailAttachment> queryByContentId(Long mailContentId){
        EmailAttachment key = new EmailAttachment();
        key.setMailContentId(mailContentId);
        return super.queryForList("EMAIL_ATTACHMENT.selectByContentId", key);
    }
}